version: '3.8'

services:
  frontend:
    image: frontend
    container_name: frontend
    build: services/frontend
    ports:
      - "4430:4430"
    restart: on-failure
    env_file: .env
  auth:
    build: services/auth
    container_name: auth
    ports:
      - "8003:8003"  # Exposing the auth service on port 8000
    restart: on-failure
  friends:
    build: services/friends
    container_name: friends
    ports:
      - "8004:8004"  # Exposing the auth service on port 8000
    restart: on-failure
  rooms:
    build: services/rooms
    container_name: rooms
    ports:
      - "8005:8005"  # Exposing the auth service on port 8000
    restart: on-failure