services:
  frontend:
    image: frontend
    container_name: frontend
    build: services/frontend
    ports:
      - "4430:4430"
    restart: on-failure
    volumes:
      - avatar_media:/var/www/media
      - frontend_service_data:/usr/share/nginx/html
    env_file: .env
    depends_on:
      - api_gateway
      - auth
      - users
      - game
      - rooms

  auth:
    build: services/auth
    image: auth
    container_name: auth
    expose:
      - "8443"
    restart: on-failure
    volumes:
      - auth_keys:/keys
      - auth_service_data:/service_code
    depends_on:
      db_auth:
        condition: service_healthy
        restart: true
    env_file: .env

  users:
    image: users
    container_name: users
    build: services/users
    expose:
      - "8443"
    restart: on-failure
    volumes:
      - users_service_data:/service_code
      - auth_keys:/keys
    depends_on:
      db_users:
        condition: service_healthy
        restart: true
      auth:
        condition: service_started
    env_file: .env

  game:
    image: game
    container_name: game
    build: services/game
    expose:
      - "8443"
    volumes:
      - auth_keys:/keys
    develop:
      watch:
        - action: sync+restart
          path: services/game/game_service/game_app/models.py
          target: /service_code/game_app/models.py
        - action: sync
          path: services/game/game_service/
          target: /service_code
    restart: on-failure
    depends_on:
      db_game:
        condition: service_healthy
        restart: true
      auth:
        condition: service_started
    env_file: .env

  avatar:
    image: avatar
    container_name: avatar
    build: services/avatar
    expose:
      - "8443"
    volumes:
      - avatar_service_data:/service_code
      - avatar_media:/media
      - auth_keys:/keys
    restart: on-failure
    depends_on:
      db_avatar:
        condition: service_healthy
        restart: true
      auth:
        condition: service_started
    env_file: .env

  api_gateway:
    image: api_gateway
    container_name: api_gateway
    build: services/api_gateway
    develop:
      watch:
        - action: sync
          path: services/api_gateway/api_gateway_service/
          target: /service_code/
    expose:
      - "8443"
    restart: on-failure
    env_file: .env

  rooms:
    image: rooms
    build: services/rooms
    container_name: rooms
    volumes:
      - auth_keys:/keys
    develop:
      watch:
        - action: sync+restart
          path: services/rooms/rooms_service/rooms_app/models.py
          target: /service_code/rooms_app/models.py
        - action: sync
          path: services/rooms/rooms_service/
          target: /service_code/
    expose:
      - "8443"
    restart: on-failure
    depends_on:
      db_rooms:
        condition: service_healthy
        restart: true
      auth:
        condition: service_started
    env_file: .env

  tournament:
    image: tournament
    build: services/tournament
    container_name: tournament
    volumes:
      - auth_keys:/keys
    develop:
      watch:
        - action: sync+restart
          path: services/tournament/tournament_service/tournament_app/models.py
          target: /service_code/tournament_app/models.py
        - action: sync
          path: services/tournament/tournament_service/
          target: /service_code/
    expose:
      - "8443"
    restart: on-failure
    depends_on:
      db_tournament:
        condition: service_healthy
        restart: true
      auth:
        condition: service_started
    env_file: .env

  db_auth:
    image: db_auth
    container_name: db_auth
    build: services/db_auth
    restart: on-failure
    env_file: .env
    expose:
      - '5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1m30s
      start_period: 30s
      start_interval: 5s

  db_avatar:
    image: db_avatar
    container_name: db_avatar
    build: services/db_avatar
    restart: on-failure
    env_file: .env
    expose:
      - '5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1m30s
      start_period: 30s
      start_interval: 5s

  db_game:
    image: db_game
    container_name: db_game
    build: services/db_game
    restart: on-failure
    env_file: .env
    expose:
      - '5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1m30s
      start_period: 30s
      start_interval: 5s

  db_rooms:
    image: db_rooms
    container_name: db_rooms
    build: services/db_rooms
    restart: on-failure
    env_file: .env
    expose:
      - '5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1m30s
      start_period: 30s
      start_interval: 5s

  db_tournament:
    image: db_tournament
    container_name: db_tournament
    build: services/db_tournament
    restart: on-failure
    env_file: .env
    expose:
      - '5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1m30s
      start_period: 30s
      start_interval: 5s

  db_users:
    image: db_users
    container_name: db_users
    build: services/db_users
    restart: on-failure
    env_file: .env
    expose:
      - '5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1m30s
      start_period: 30s
      start_interval: 5s

  redis:
    image: "redis:bullseye"
    expose:
      - '6379'

volumes:
  auth_keys:

  auth_service_data:
    name: auth_service_data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $PWD/srcs/services/auth/auth_service
  
  frontend_service_data:
    name: frontend_service_data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $PWD/srcs/services/frontend/public

  friends_service_data:
    name: friends_service_data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $PWD/srcs/services/friends/friends_service

  users_service_data:
    name: users_service_data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $PWD/srcs/services/users/users_service

  avatar_service_data:
    name: avatar_service_data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $PWD/srcs/services/avatar/avatar_service

  avatar_media:
    name: avatar_media
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $PWD/srcs/services/avatar_media
