

services:
  frontend:
    image: frontend
    container_name: frontend
    build: services/frontend
    ports:
      - "4430:4430"
    restart: on-failure
    env_file: .env
    depends_on:
      - api_gateway
      - auth
      - users
      - game
      - rooms


  auth:
    build: services/auth
    image: auth
    container_name: auth
    expose:
      - "8443" 
    restart: on-failure
    volumes:
      - auth_keys:/keys
      - auth_service_data:/service_code
    depends_on:
      - db_auth
    env_file: .env

  users:
    image: users
    container_name: users
    build: services/users
    expose:
      - "8443"
    restart: on-failure
    volumes:
      - users_service_data:/service_code
      - auth_keys:/keys
    depends_on:
      - db_users
    env_file: .env

  game:
    image: game
    container_name: game
    build: services/game
    expose:
      - "8443"
    volumes:
      - game_service_data:/service_code
      - auth_keys:/keys
    restart: on-failure
    depends_on:
      - db_game
    env_file: .env

  api_gateway:
    image: api_gateway
    container_name: api_gateway
    build: services/api_gateway
    volumes:
      - api_gateway_service_data:/service_code
    expose:
      - "8443"
    restart: on-failure

  rooms:
    image: rooms
    build: services/rooms
    container_name: rooms
    volumes:
      - rooms_service_data:/service_code
      - auth_keys:/keys
    expose:
      - "8443"
    restart: on-failure
    depends_on:
      - db_rooms
    env_file: .env

  db_auth:
    image: db_auth
    container_name: db_auth
    build: services/db_auth
    restart: on-failure
    env_file: .env
    expose:
      - '5432'

  db_game:
    image: db_game
    container_name: db_game
    build: services/db_game
    restart: on-failure
    env_file: .env
    expose:
      - '5432'

  db_rooms:
    image: db_rooms
    container_name: db_rooms
    build: services/db_rooms
    restart: on-failure
    env_file: .env
    expose:
      - '5432'

  db_users:
    image: db_users
    container_name: db_users
    build: services/db_users
    restart: on-failure
    env_file: .env
    expose:
      - '5432'

volumes:
  auth_keys:

  auth_service_data:
    name: auth_service_data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $PWD/srcs/services/auth/auth_service

  api_gateway_service_data:
    name: api_gateway_service_data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $PWD/srcs/services/api_gateway/api_gateway_service
  
  friends_service_data:
    name: friends_service_data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $PWD/srcs/services/friends/friends_service
 
  users_service_data:
    name: users_service_data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $PWD/srcs/services/users/users_service

  game_service_data:
    name: game_service_data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $PWD/srcs/services/game/game_service

  rooms_service_data:
    name: rooms_service_data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $PWD/srcs/services/rooms/rooms_service
