version: '3.8'

services:
  frontend:
    image: frontend
    container_name: frontend
    build: services/frontend
    ports:
      - "4430:4430"
    restart: on-failure
    env_file: .env
    depends_on:
      - auth

  auth:
    build: services/auth
    container_name: auth
    ports:
      - "8003" 
    restart: on-failure
    volumes:
      - auth_keys:/keys
    depends_on:
      - db_auth
    env_file: .env

  users:
    image: users
    container_name: users
    build: services/users
    ports:
      - "8000"
    restart: on-failure
    volumes:
      - auth_keys:/keys
    depends_on:
      - db_users
    env_file: .env

  game:
    image: game
    container_name: game
    build: services/game
    ports:
      - "8001"
    restart: on-failure
    depends_on:
      - db_game
    env_file: .env

  pendu:
    image: pendu
    container_name: pendu
    build: services/pendu
    ports:
      - "8006"
    restart: on-failure
    depends_on:
      - db_pendu
    env_file: .env

  api_gateway:
    image: api_gateway
    container_name: api_gateway
    build: services/api_gateway
    ports:
      - "8002"
    restart: on-failure

  # friends:
  #   build: services/friends
  #   container_name: friends
  #   ports:
  #     - "5"  # Exposing the auth service on port 8000
  #   restart: on-failure
  #   depends_on:
  #     - db_friends
  #   env_file: .env

  # rooms:
  #   build: services/rooms
  #   container_name: rooms
  #   ports:
  #     - "8005"  # Exposing the auth service on port 8000
  #   restart: on-failure
  #   depends_on:
  #     - db_rooms
  #   env_file: .env

  db_auth:
    image: db_auth
    container_name: db_auth
    build: services/db_auth
    restart: on-failure
    env_file: .env
    ports:
      - '5432'

  db_game:
    image: db_game
    container_name: db_game
    build: services/db_game
    restart: on-failure
    env_file: .env
    ports:
      - '5432'

  db_pendu:
    image: db_pendu
    container_name: db_pendu
    build: services/db_pendu
    restart: on-failure
    env_file: .env
    ports:
      - '5432'

  # db_friends:
  #   image: db_friends
  #   container_name: db_friends
  #   build: services/db_friends
  #   restart: on-failure
  #   env_file: .env
  #   ports:
  #     - '5432'
  # db_rooms:
  #   image: db_rooms
  #   container_name: db_rooms
  #   build: services/db_rooms
  #   restart: on-failure
  #   env_file: .env
  #   ports:
  #     - '5432'

  db_users:
    image: db_users
    container_name: db_users
    build: services/db_users
    restart: on-failure
    env_file: .env
    ports:
      - '5432'

volumes:
  auth_keys:
