
POST https://localhost:4430/api/auth/signup/
Content-Type: application/json

{
  "username": "sinuse_pseudo",
  "password": "pass123456",
  "email": "sinuse@gmail.com"
}

###
DELETE  https://localhost:4430/api/auth/delete/singeuse_pseudo/
Content-Type: application/json

{
  "username": "singeuse_pseudo",
}
###


POST https://localhost:4430/api/auth/token/
Content-Type: application/json

{
  "username": "sinuse_pseudo",
  "password": "pass123456"
}
###

GET https://localhost:4430/api/auth/singeuse_pseudo/

###
GET https://localhost:4430/api/auth/protected/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1ODMwNzQwLCJpYXQiOjE3MzU4MjUzNDAsImp0aSI6IjAwZjI3MTBkNTdlMzRhNjVhN2E1ZWYyNmU2MTYwM2I5IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJzaW51c2VfcHNldWRvIn0.KWjQgAwPcl99Wu5lF0r6DZ3MkT69iEbgfNVVXzyQ3QMxb39zk9LBzhIV12tkTwRkBXosb3VlEqsUApt75cT0sEgLOLGSS5o53yoxkOYWgOiAfsm9NvaKF45fRf4EKeEEEVhvXpKic2_lOXxf1lFZRqFdcMyMwRFsW9EhKDUyJya7mqp36_TK0QE32f4Z7upQZm-GAR81OjVIEnqpgntCOOHr65brDtcup75FV8wvJtV5MntmmfpXezDONkyVyZ8ZATAeF0mEr0VJZ7_0L9RVszCF8pC0I_OfXnwfV-DcRMznPRpVkEa-IFyk5UMI39Menm9KVPkkEp5ySsUWLSZfMQ