
POST https://localhost:4430/api/auth/signup/
Content-Type: application/json

{
  "username": "sinuse_pseudo",
  "password": "pass123456",
  "email": "sinuse@gmail.com"
}

###
DELETE  https://localhost:4430/api/auth/delete/singeuse_pseudo/
Content-Type: application/json

{
  "username": "singeuse_pseudo",
}
###


POST https://localhost:4430/api/auth/token/
Content-Type: application/json

{
  "username": "sinuse_pseudo",
  "password": "pass123456"
}
###

GET https://localhost:4430/api/auth/sineuse_pseudo/

###Ajouter le token recu
GET https://localhost:4430/api/users/protected/
