
#add user to db
POST https://localhost:4430/api/auth/signup/
Content-Type: application/json

{
  "username": "test_user",
  "password": "pass123456",
  "email": "test_user@gmail.com"
}
###
#get user token
POST https://localhost:4430/api/auth/token/
Content-Type: application/json

{
  "username": "test_user",
  "password": "pass123456"
}
###
#get service token
POST https://localhost:4430/api/auth/service-token/
Content-Type: application/json

{
  "service_name": "auth",
  "password": "private"
}


###
#check if service can access protected view
GET https://localhost:4430/api/auth/protected_service/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX25hbWUiOiJhdXRoIiwiZXhwIjoxNzM2Mjk3MTc5LCJpYXQiOjE3MzYyNTM5Nzl9.ELpgZkHpG_-X9Bs4KlvhQeof29tBHx4a54FdXgrDTETTSdA_K8qgLIhjziZsgWrNJooV3sNBceNKemcwIjAvMaLZcBTX4E34fN-H6LI6T7gSijAco2SIhurWIdftjzQLSrFig4o7IJ2wluFua_DK86L5ZZ_AE8yUVHskgFZx1wAv5GD-gap3gz4cdm-rPN6P-s5QKbSuuUo2URFCrkZ-uWqR_F9Pbd_Z_YEWjrQMp_S0bm-Iomjxxf6sRVA1DwRIYfy7TLU29hHS_B4z6_rf9PFkuSrD2lrt6whoQVdVVOsaV0biKhlka4QXJLPvmQX1qpX22UAHDkVdibh_HysHAg

###
#check if bad input can access protected view
GET https://localhost:4430/api/auth/protected_service/


###
#check if invalid token can access protected view
GET https://localhost:4430/api/auth/protected_service/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX25hbWUiOiJhdXRoIiwiZXhwIjoxNzM2Mjk0NzM5LCJpYXQiOjE3MzYyNTE1Mzl9.W6JN7Oahw0qRwd3m36_pJu0tmb8VdHCC3KJElPW5C94fReFj6i_l7_NSVGE2CCew6tvtjLEWkbSop6Z8z_1B9PQW6Mw2TNdxSc1K4jBzL6q1t8AxpV6_I1QxNpqCFtRYHQjf2IOJRYqNlsQWGpZGmIUlmCd7bjTJB2Az1D9MH71uZp0mJ-sp4HUWljk2G2W0tZXJB_MvAJx3y1MmkX1O-hBiWugo7tYOTZpUDYPU4ryHYgK2ihLfT6GYztg23VZF9qmRA7X_cdKH0JXKobOICRPmXACb2d9aSiSz-Be16rP9M7tXJ1muGKrAWAD_Ptp4KtQ3QoJf0OuAYngTM2Hyqw



###
#check if user can access protected view
GET https://localhost:4430/api/auth/protected_user/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2MzY1NjM3LCJpYXQiOjE3MzYzNjAyMzcsImp0aSI6ImU2OWQ1MzNmMjVkNzQ1MDlhY2Q3NDhlYzUwOWRhYzhkIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.UUouWieQ9FT-89mZK4mEkER8EzoPidGDTjgIc1B132iOfjkDMDl9FmL2w5DU_VzzIh4E7SfAULenS0xYLH6AZVUXopLUqDeLsQzLUlIPD12_Fnl-kO423YTp5pLthbtAbIgdZle7Lb42VFJcdpT6BrOeqaYQsPObqf2bb2Asf-ZX6U6WrJk5ag2giaACr4NcvSfeKzlubipPcuF-cdH-hoekIXZKUFRRARYpFr2ddEuVfoMJ5cY2-29U6PHFIQVj102OoPSl6LDDLLRDecnSohK1x96vMrweFVb33Xse-vFJdASj-HaCQ0fRfUk2R8zWHsowiGptbxetCscLXbRUNQ

###
#check if bad input can access protected view
GET https://localhost:4430/api/auth/protected_user/


###
#check if invalid token can access protected view
GET https://localhost:4430/api/auth/protected_user/
Authorization: Bearer <invaliduser token>

###
#get 
GET https://localhost:4430/api/auth/test_user/
Authorization: Bearer <user token>
###

DELETE  https://localhost:4430/api/auth/delete/test_user/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2Mjc0MzcwLCJpYXQiOjE3MzYyNjg5NzAsImp0aSI6ImM1YWNlMWMxNzliZjQwNTliNGE2NmMzNjIyODI2YjViIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.ZYt2wagRLiDtBaU2peGC6Z0RALJ0sr2yXI3ZVif6xXpV1SS5Va03KCs3CuLqS4H9pBUqR3ODAzLn2SiXG2cw7Tt1HsCliG0kZYFbpvQjQofNyGq_CKsY2uHa0BQ8ksm9olDnZgkC9LSo4EoYUQNcGl0GfbvUMFmrb955WYFov6M_jic6vbJS_xv9-9fNSFJWJa7K9yuv7-ASi-gaocUqtTQMS47SHjSa4oG6-JAJm_4HhL_XQ0b9aL0uUt3f8MiRJ3YYGWKkLlciE3rdXJm7Q7bc_fwPqB52yPGAeOWHoxVXAnYtld9NBzL7ou6HOhrL-Covxq3TE9znnnTEc0tINg

