###
PATCH  https://localhost:4430/api/auth/change-password/tresiii/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5MjAzNjIwLCJpYXQiOjE3MzkxOTgyMjAsImp0aSI6ImMzZmEwNDg2ZGFlNjRiMWI5M2RmOTliYzc0ZDc1NzEzIiwidXNlcl9pZCI6MywidXNlcm5hbWUiOiJ0cmVzaWlpIn0.Gde_9LPhji0TGqcX5p61TA62KvFb9m_kXqV7HYwK8Z-y_XxsY94hHxn9JFIAVY6l2vXECjoRmc1Mu6CFxWAl4JezRLK1BYXkfKi3phd6psZsk3utXxQCLGbIwsy0-TT3TqNPQoVdFtWloFrJh2ua-D2ZsfRRgosaU8vI29He6C1UfFmdMNwvNxpzTs00MStdyMrHs-VJBTFxfZy32Kb5MRyoroLvoU7IPomSWa7ZLV9Cqzi-OVMsC2JydNy_JNX7xhqC6QmDV7bLmXEAMSfyMrGX9xApZ90JGGyG4WkTogcII_9sedDJQsNQIEPnzyA-HZHDmMns_KW-V-kYGOzGFg

{
  "password": "Pass12456!",
  "new_password": "Pass12456!",
  "new_passwor2": ""
}

###
get https://localhost:4430/api/users/status/test_user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxMTExODkyLCJpYXQiOjE3NDExMDY0OTIsImp0aSI6ImY3MTA0OWVmNTI5ZDRmMjE4MDFiZTg3Yjk2NmE4YjVmIiwidXNlcl9pZCI6MiwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.n-cZWpWKgJ31axZy8XV7xINyL75pAjxsbQ-htQWztvB5y3FhJOes_0rIov1dJxVHaSij4u9n3jJb8om5-Avnx9rpFImdjVWn0LQLgNUX5Z_itRowTri7OZJ-8T6_Ch0GCJlIy9bqDchLwt29AhOWY0Y3w5Ccd6Vg422wuaVfWVibTFnVi2C513CiAA7LtzGEPs6mz0As7LrCW85r4n2Lskft4MgaksE02Mo1Mn3nbKIIYPAb4a9kn9JdigXQWGpkAURdXImRjNkUHiE5VdjuZqSSQ15HzPAoSStb5lTE80k7ez4JnuL_kUbKLaMqpahf_pA14ux8DRSZ_2Ld7qup8g

###
patch https://localhost:4430/api/users/update_last_seen/bidoenepiii/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxMTA0NjA4LCJpYXQiOjE3NDEwOTkyMDgsImp0aSI6Ijk0YWM1ZjgyZTYyMTQzNmRhYTRlNjE0NzBhMmM3MzAwIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJiaWRvZW5lcGlpaSJ9.fysIGXWh0X7s8GYqFDze-1UkjuHoad74rQwSW-MhXFAi5Jql17w7fBAYz6bqXlmjUpnBvmQAXgVh-FboB1f6Lh6P1-MEpDO-aI-piRKA8r7evJOEHwfmzDqUkvbFQo2cpS4qIRZbyN3vMpICaDpY5eId6lj2V-LadCxk3EQ_ajiznkSFXxyzP2BdyU_0pf_OrOcATOuIMsXuRwZeKbVA1rXt6xr7dfpRk3W0QKRQ4f8iJ52298UzqYzncgTN1KAI5J-ZrDBvVJHWhFcEg1lHinCmsCSlNNgSDDuQSObiD56uCjHY411qEvocroT_WhTwjSw8MW54f0qKiFgje6PjyQ

###add user to db

post https://localhost:4430/api/auth/signup/
Content-Type: application/json

{
  "username": "test2",
  "password": "Pass12456!",
  "email": "dei2i@gmeail.com"
}
###
#get user token
POST https://localhost:4430/api/auth/token/
Content-Type: application/json

{
  "username": "test2",
  "password": "Pass12456!",
  "otp": ""

}

###


PATCH https://localhost:4430/api/users/update_last_seen/test2/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQyNDAyNjQ1LCJpYXQiOjE3NDIzOTcyNDUsImp0aSI6Ijk4ZTI3Nzg1NDZkNDQyYmZiMWMxNTc0OTA1OTZhZDFlIiwidXNlcl9pZCI6MiwidXNlcm5hbWUiOiJ0ZXN0MiJ9.RhVkfbm6Mcn9i_qGkPtKDPMmgN_JsRNTDaVi32Klq7iwecpxLdhf9oI0aqkYlvJL1lIEmXDbtw2jgFVFE9CM4Tya4YyEPSDcyTAq76aelcMk69nxwdY-CrHJfu2-s3KqwDXBUYwTsIEwZE4eoTVz0de8rlEn7sDsMgrrDm-BB6e_vVWuMvUiZEvVpO8n2Idq0KlkVFTMVhxzkU-zOSSkWl3_48NdWSiBD2QWHTz3LSoyfXSWjTI3ySdJpnt6kb8GuyKyvuUX9NtcTWWt5JRwvMNL_59jJS4JsBLzyV4r4-JxJMZ9LKVH_cAcPSLzoGq_g3yOYSmK1_rQTdb29Vp6ag
Content-Type: application/json

{
  "isOnline": false
}
###

PATCH  https://localhost:4430/api/users/test1/friends/add/test2/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQyNDAyNTU5LCJpYXQiOjE3NDIzOTcxNTksImp0aSI6IjAxYTE4ZmM1ODQ0MTRkYjI5MGIxOTNmZGE3MzEyNjlkIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0MSJ9.JkKJ0CLlkZZ1WVB-QGsRny9lkCmqLDDsxRM407qz64wcWJC06XmpcPbsBt2XZOnkXu83FB0I697xkKq0cSBLIvdyYos9Cnvz8bTdFvSj630qH7JLv8_pdUgGC65n88NTueO7OKZLA6womlDfv0KsFg4OZYDpOjVI4XvfARr7i-ddoE2skzz4oJ3VY3swgNsdKB7LYLTabMI1A1G8KIMl0wj52i4-Id5vowhR9HBrZGRyubSORcS67A1m0QOFPR0vu2VX2qawuFTT627dI12YWHmJU8Fz5lB5Ba7uCueaEYnC5o9QSUKpSi_fBuus7dgHbaZ7MA5gq9J7iWR9szRAeA
Content-Type: application/json


###

GET  https://localhost:4430/api/users/test1/friends/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQyNDAyNTU5LCJpYXQiOjE3NDIzOTcxNTksImp0aSI6IjAxYTE4ZmM1ODQ0MTRkYjI5MGIxOTNmZGE3MzEyNjlkIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0MSJ9.JkKJ0CLlkZZ1WVB-QGsRny9lkCmqLDDsxRM407qz64wcWJC06XmpcPbsBt2XZOnkXu83FB0I697xkKq0cSBLIvdyYos9Cnvz8bTdFvSj630qH7JLv8_pdUgGC65n88NTueO7OKZLA6womlDfv0KsFg4OZYDpOjVI4XvfARr7i-ddoE2skzz4oJ3VY3swgNsdKB7LYLTabMI1A1G8KIMl0wj52i4-Id5vowhR9HBrZGRyubSORcS67A1m0QOFPR0vu2VX2qawuFTT627dI12YWHmJU8Fz5lB5Ba7uCueaEYnC5o9QSUKpSi_fBuus7dgHbaZ7MA5gq9J7iWR9szRAeA
Content-Type: application/json

###
#get service token
POST https://localhost:4430/api/auth/service-token/
Content-Type: application/json

{
  "service_name": "auth",
  "password": "private"
}

###
PATCH https://localhost:4430/api/auth/update/dd/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5NDYxMzI0LCJpYXQiOjE3Mzk0NTU5MjQsImp0aSI6IjJhOWZjMTBhNjdhYjQ3NTE5YzE4ZmQzOTIzYjJjMjU5IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJkZCJ9.Auyqsil6Iw3PB6wk4wP5re6OCjiwJFkt6BXoR5MqAZQp_yplTpdx-EcIZQqypAaomxhHUYR-JIxhIZyoEU9-fRbgPJKFX8Jaj5_koW8AfNgjqyRlP8LjU-vBty6cdM9nJsbm5maQIaEHgy3LxanOCe5AvlFF9Z5oSiMjRgSDHOAbJUcftggvizsa9YO4qX3dHHMNsiBD04qd1ZoEGIphD2_B2dOd2FNOiK1_uFJsQSfytlDI417_Bx5U4apVdw5kCjmf6EwFPOy_3jVNNuzyiHq7GHL9RTEJPBRR7ZIdqHTD04yJ-vFbAOeLKBAUDz3mnSdcbkY_bxyosZGJy95Nvw

{
  "username": "dd",
  "old_username": "dd",
  "new_username": "ok"
}

###
PATCH https://localhost:4430/api/users/bidoenep/friends/add/bidoenep2/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwNDEwNjgxLCJpYXQiOjE3NDA0MDUyODEsImp0aSI6IjgyYzc3M2VlMDViZjRjNjE5MTNjNjdiNTk1MjE5NWRjIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJiaWRvZW5lcCJ9.nq-n1ymKeYWwiexsy9ePu03qmi86snu5DJ3-IVdOAoTXv-nsCG267r6NhfXmy12h7mCayLJ2YTb73fKYFXfx3CX7qtdDIXFOAsF7XMLnrdFCbOnFk-0pgROzfhq9hisDhTYkPoF7flEudX6MJ5PrFR6FNZhYPvqq9ojiNslpS8YJU4WR5PeEka6vvzwp13IbRYIOhEm9BVhpt-wt9uPDyGXc_4zb9cYRzoC-piiBUYDRtsvkNvltauEud0kK9JFFqR6G-3iUhydZsUVRv-6j6X5MMW7VQTzqrAuLhjPxOVVdRv6QtkK5F2_uCmhl31mlX1zhhP2H4LFIvcSLqcNo3g

###
PATCH https://localhost:4430/api/avatar/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4NzA5OTI0LCJpYXQiOjE3Mzg3MDQ1MjQsImp0aSI6IjQ4OTQ4MDUzMDRkZTQwNzViNzQ1NTgzZWYxMzkxOGYyIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0Ml91c2VyIn0.YuLIVN91Q3K6SBv5X7hpD1_qpOlm2twPvknS674hM_YuCFKy6BdGrzl6qyGWcdGcEAVA4SArgGJoROwQfylKpS8TP55Ju_b1HhanFjn7TQU1vxj6kHbxbJwJnx4iy6bW4wS2TXSGCvzvgTzrgKQHf09JNkIUfjwI-Trb4EdqjWZr1QjNtOL7w4608KyWimBkMTzCnEPayn26qMCI0UOyZXL6yFNXKz-nWW3SNgFp7G2auF8aRBUZF6IZ0Caef4ZardI8VYOFQKdYXujIKBW1Ff08-q33Pw3i21vAPLfNx8zH6rqAJB0ebUgYdvF7vaUmgiLOABYolRu5eZT4OMK6Iw

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="default.jpg"
Content-Type: image/jpeg

default.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW--
####
GET https://localhost:4430/api/game
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5OTc4NDI4LCJpYXQiOjE3Mzk5NzMwMjgsImp0aSI6ImQ2MzhiNWJiZGZiNDQ3N2M4NmJkOGQ3NjZmYTBmNmY0IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJiaWRvbiJ9.a5QjISKPUWzIHHb9CyBS5B0b-9OTO8jlV08pxmaU3gu0BApEuDgTfkuXH8imTPz2l3SrKaDw5JBVfN99ktoYqyAzeyn_AtJ2UXBV_TXeU_xCQaEL1-3TbeFYHTdJ9vRplBf9OPGzZ-pd9vNOMiQVfAAiPOhlaJKyAmryfncrjrfcLUNHTNYwEUkXuE0KaQJqdV2Zw0XDTyujCBKVk1shLhVLTzJlJxlt1PBnsvK25olYcUkmyYKjmyf4oSUGDD12uwQrDpVauoEYJLWrAc_ATe0P_AX4xZquFZopXgOYf84EdD352He28qskQ_9-BMp2Fy0IjIBF8TwPggerbP2vhQ


###
#check if invalid token can access protected view
GET https://localhost:4430/api/users/protected/service/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX25hbWUiOiJhdXRoIiwiZXhwIjoxNzM4MDM3MzczLCJpYXQiOjE3Mzc5OTQxNzN9.d3051RYzd7AApiRDWzFfpKZql4FBDBFTqQmWfrE7r1UfOInDqppe4qDxreU2b-nO5veIho2jb-VP6YmxxLUrxLW8ULPNWYIl379NCRuJfcxnSHkEOqipPXLS1UU-EO1tZ3MK_8rPvGX3J_tdwXnCjNQtQqKf2S-L0apCifEvoeS_YpwPNXsgqEni0-XXT9BzLLNr-ddp8kxAWrDm_jW1_m1s6B7iS2y6SV-Pt41AEbYh5XOIA3t1ZMLdLMi2GeX6sbQffDb4fp5GLPlOwb-0v-6iVrS4Tci4POIp-a40RnlMTe_yH18IZlt7EpslnEScmbBp_zjReo6HO6AL4YVS_A
###
#check if user can access protected view
GET https://localhost:4430/api/auth/protected_user/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTk3ODAzLCJpYXQiOjE3Mzc5OTI0MDMsImp0aSI6ImIyNTk0ZTNhODM0ODRhYjFhZDVkNWY5ZDcxMWQyMWUxIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0Ml91c2VyIn0.JXCGYshHfBApxbheWcMim5ifgL69pPt8zE-yDyvRKObCQW5ZIJzX__TDqwRlEyYKn2bvZvXSiNja6wlvM2O32VxMiJoeGuYSSbmdS_ZuvXmZQ20InrC2gTRp-RlmUnpsRH7e6eVGjM_Gn3mP5hCN2wPFHF57KCwpVlRI0mSzIi8CPIs6Z4SsteOAo2G7NsthRYtTbiS0LhQoyBoMGyq6pQ1pY95eJRX-jvAbhNHImN8zD2oODB33uro1lRkArDmY_nggIt3ZWOQqM7iuDhrThhi_paFvv7o3mIB1FdNK6zqErFS7UBErV0Nm0s0RSHcJLLd5hMYh_t7i3GWRVpGQUg

###
#check if bad input can access protected view
GET https://localhost:4430/api/auth/protected_user/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2OTcxNTU3LCJpYXQiOjE3MzY5NjYxNTcsImp0aSI6IjQxMzA1ZTcyNTViYjQyMTY4NDExYjkyNzljNTExZWU2IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.lnHEq4SK8S__SqOzKd4Xn88QQi82Wve5tx58YvhXZUBRkbU35bmnB_kp7525Jes36AY5sbC9YDiVZEriXNDMsy7-kAwvsSCpglKFy5mGxfOiaf8ndRiiqgySyn9B1Lbd5eWFfqesJ6aSaotwXuiwDvSh6GdNnuOtmSJTqeDXKOIU-UYPL4-sUfbxiCSygu7X7oKB27YbUvYN1r9XB6-zMoM4GBTfTYdQ_2aoK1Ch6LJYyh9-DlnGAVmJffdMA8T8cvU73xSbVowtLc-hfHGe8hpXPtmuMDHLclLTK07L5s2HwV82jrICaTpjXOjVJ7lR7saRQ9F8enxQLC9S9ZlDow

###
#check if invalid token can access protected view
GET https://localhost:4430/api/game/protected/user/
Authorization: Bearer iyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2OTY5NDE2LCJpYXQiOjE3MzY5NjQwMTYsImp0aSI6ImVjY2Q2MmFmMTY5ZDRlY2FhMzllOGE4NWRlZDVkODc4IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.OzlT1gv0YQby-SdXYgyCO-PP53V0Vd97uoTlnWDZFvhcpItz9PsgZmVXT48mIZZ-nrITSruIqKgLNAyukDTiU1ZQTyZggqE9nrvvFzPs1s_c1SsdBBV9SHvRd13b7L7cO1KXSN_iZA5Dg9AsfdzHtIfPK2E2a-pLj9Yv-0bk8kBiWvYz8WkFUSz9wcMg0eMy-6S9-P0nM9OYXi3eLvlWkOJ3YE-bW8T-JbVgaUncMXmWEB8W5YfJsVuqx1tRMU20724ylRrugVFICzlmc3x0XqZ-UjVpVWeytLUwSSj3lmXHylhXFzRllu0FN0lN4B9AsrQHDvmghnk1AxKcJ1e8nA

###
#get
GET https://localhost:4430/api/auth/test_user/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2OTcyMTc4LCJpYXQiOjE3MzY5NjY3NzgsImp0aSI6IjEwZGYwZTNiODUyZDQ0ZTk5MTc1YzczOTQ4NDdkNGY4IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.ClBkyJUt94p8eoKVXznIlpJrJgOMH08p4z4gyEwCytqw4J_h3Rir1NB0k_gAjrldK9uhSXIHK-psiJMde9Gf5C9J-5FUB4-eXxu7bC6GtQMDITz6_nmoaOLRDEk8gdj8FPvnTbs25uFebkwFvo2Rbuls7B6BhKr-dTbFAtFMh5dsaK2m7sL3J1ez3X6IbyCb_lqfqKr5vqmQZzxuAGrIY8oAWnZiR3K5aOLyHStbX-K7LM3cDMefOognvbTgb51gmwXtnVY-QBxvhuAujYwPUOD9bVUco22LjmLziakggoV765uORJhke1q4mCMSXONRqB-GVz6znpBgioAgn_nBtQ
###

DELETE  https://localhost:4430/api/auth/delete/tresiii/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5MjgyMDY5LCJpYXQiOjE3MzkyNzY2NjksImp0aSI6ImJhOTI3YjU5YzQ2YjRjZDg4MGU4ZGE3YzI0YWQzNmE3IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0cmVzaWlpIn0.WtiRD15Lu47ditE6VcFic9kRPyHdcbH7IywDwUOPhfCtA_f_mue49gok6vN879dOalM-0Ms0-txMOwcmrGblR3xhle_X4skU0JfRP7YVuOakS7k_N4un0jFDhVjQXeJbM1vMMeIO0pb7DUcqIZxTjS_DRzGt4BHwGI3DoGYz-W7Q-3_odFbhCEDcdUwpPALmwC0F4w-urv8CV95J3Gy4V-WFJLFUJF4H5suvXI9vduFPPWRw0utsuWTlOElKBQ9aYy4xTHIZC_KIzlJmp2pQ0jxLT_goK6luqqTQc1h-qL6Aznk_Dhgl2XGAuiIXitn-mycluuttXQkk5d04QM_T3Q
###

POST https://localhost:4430/api/auth/logout/
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0MDMyMTg5NC4yMzE4MywiaWF0IjoxNzQwMjM1NDk0LCJqdGkiOiI2ZTFkZDc5ZTRkMzI0YzM3YjU5M2FmZmI5ZTVhNDMzZSIsInVzZXJfaWQiOjEsInVzZXJuYW1lIjoidGVzdGkifQ.mApQhZbAXHUF9u2Prlc96hfQncd1g0zeCEpxToHi_b6ia9v9pZdZCV6kpxicJLXoh_umTZ9sohzOoJgWU7w_QMnN3CUK0unIsMfjBnG-9ZFSGpf9gatnUfJ5d8Qicu_9sJz5tYxGZV2xc4CYkT2YUVs5JgDGvqpppZNVVMgdNTKbLnNfz0GGYT4PU_zXfXI9oXrGiSofQ8tu68Tt0xPdyqxHSsd6iMDENTgisyvjhLc8qe7ch4bPlnLrh772MO9YXm6jjIxYftj0WrtxM_WK1TGu8m-oIzQpBI8TKIFUX5Rlh3YpI0PhlA6WNTLpyxhpwawSjDZyFdMgm34rhWXDNQ"
}

###


PATCH https://localhost:4430/api/users/update_last_seen/test1/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQyNDAxODIxLCJpYXQiOjE3NDIzOTY0MjEsImp0aSI6ImZlODE2YmJlZDRlMTQ3YzhhMzczZGRmMjNhNzU4ZjJmIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0MSJ9.XNEY0gm3Dfajeeup9Fnm4sY2aDtZkg0pcnuBsQFKkFb2lcnZfR_8T6nfA-cpXHqNYBhOE5ikZlXHFz0OdjiRjDAEoT_pSzlajkyJT4cXFFbbxxVKq3nnrpEI-vGGaDx9O2viG-mDqghMoD4SbtuddNcb_wJ6_wQCf-vhZzbcBC4pR5gBP_-nbhVabHqgRtlwacW3X6Bs-PouO8gtwCBH4wROQzN_6w_ACtCHZrfTqx6Kx4go3wOOzdLC2ZSI3ncylUbHtSYfvJtZcmgtx7uuca1suJFTFOwysxAGsvliM3Q3518MaICHZAbi9rrnX0AgXz0mW1mQ986alEyyBCK0eQ
Content-Type: application/json

{
  "name": "delete"
}

###
POST https://localhost:4430/api/auth/refresh/
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0MjM0NDE4NiwiaWF0IjoxNzQyMzAwOTg2LCJqdGkiOiIwYTNlOWFmNzQyYzI0YjllYWJmYmYyYmEwMGMzZTRkZCIsInVzZXJfaWQiOjEsInVzZXJuYW1lIjoidGVzdDEifQ.AYLsski2QcPMfQKTxeRoCDWVkiAPg2cS9XPzoTE515Zg0XQ3jJDZdxsbaB6pvAajR9bV0d-jfqLX3eVX88kal1SKeTjzX1lBaOBi9lUSTAXdH9KqFmfKW6fPWnB81djd89MLHgDmazH_AJ25tklAv9gYycpySsgFiQ-fmAx92Lw8busg8birUcf-COgkmgLnmFEWCZAiZSh_9NmsTHgx7GJjxJWbvS8ksQgoWRZXPc98dbIlnCbclftnFVLGL_6VepmJFteSHv5WIF0UIRqtty4nL_lt3LOCGnGM2VzJgZ1iclJq8NvI9jgssnWOoWytaP9QquoKgqLHSlxzb_y7bw"
}