###

GET https://localhost:4430/api/users/test
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX25hbWUiOiJhdXRoIiwiZXhwIjoxNzM4NzMxNzQyLCJpYXQiOjE3Mzg2ODg1NDJ9.AklLzzHNGshk-iaZrp0qQ4OnSeqCPH7WRccCxs4Fb0Xd2unqfm2tPXu8AfsZbpxe88RYU7ZgFH9cq9U5jOMzhHPKWGW5vHaJVQojK2mtE3rNAETF3Uy08BLK_c7XvcWlCeAfBv8ibOoyTidQXTjtOEZzmbiPfwO6DdinzWDWo47dswsOkZao5j8iGhDvWQaEPGdpspShreLKmgrjd_vJGlJhjIsjeY4vLZRgdcMDZbzj8G7SfKwVVGsiFSUNF6y02rKy2SPsqYeNXq3G-Lmh277nRcAE2_A9Z6l2Zcs_dLtJ5et22IxfkZZXqq5H2M9xjKgr633depPsA3u_a6Ilig
###add user to db
POST https://localhost:4430/api/auth/signup/
Content-Type: application/json

{
  "username": "test2_user",
  "password": "pass123456",
  "email": "test2_user@gmail.com"
}
###
#get user token
POST https://localhost:4430/api/auth/token/
Content-Type: application/json

{
  "username": "test2_user",
  "password": "pass123456"
}
###
#get service token
POST https://localhost:4430/api/auth/service-token/
Content-Type: application/json

{
  "service_name": "auth",
  "password": "private"
}

###
PATCH https://localhost:4430/api/avatar/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX25hbWUiOiJhdXRoIiwiZXhwIjoxNzM4ODIwMDA2LCJpYXQiOjE3Mzg3NzY4MDZ9.tDkqg88fLNjm1qdPQJJPU4yJJmLptgnzhQH4ozT45EBflcyURrok4CIMKY2JzTC0A0cnG7iBDyMIx4AHbLbfYxFFlp39oLXzXISLtPpMlYEahzVm6sCyV6PwW9kNBKxBRCwC2KcTj3_XYdfm8g4ynx02Rbv5Ou-KKjhQLG-FLlv6LYBCy9aMYqeDLWnsasiSRGIeitVzICSfiKGObowRMaceoDgSyJBLA2jZzzxg-qtLOjaOf4TBIwzn7DBVwQoWXGfvzPx3Ixz-cpOyRDaMfjQSU1LiQ7jcwL4a5fN3DCLdlPKc1BwFbmDN1Rb0j1wLTgxYruP-4Euuw-VH4H5EjQ
Content-Type: application/json

{
  "old_username" : "test2_user",
  "new_username" : "test3_user"
}

###
patch https://localhost:4430/api/users/test2_user/avatar/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX25hbWUiOiJhdmF0YXIiLCJleHAiOjE3Mzg3NDY1NTksImlhdCI6MTczODcwMzM1OX0.wOXrCcxhVT8e4gGTx-XdCe3UViNARVfb2oGp3KDwaxGAXxHF0b0_fxfCOAN-WSWh5M-d1BrSfKBd0Z75y2Auhko-CIav6UnPn-9MW_-3KlojpqflSyutv-nKPuba07M7C99i4cjefqA6WU9nbGC3YGviTWNZRSAf4AONTj13-Tx508-ZlBMHrzwZQ2XJrpkqat-PY0YSNEOrwPCfzEN1tGARghElPbMWX-V8uJzUdJx4d6Pb7MsUy2Rm-FSZc8PIG64rMa-WlO2YbdwHLUjYTUs7hRxSmu5C-5AQnYxAHvu_3RkuF9CPTsHaslAGHgn8R4SV0ictHOaxv8fEhKaQmA

###
PATCH https://localhost:4430/api/avatar/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4NzA5OTI0LCJpYXQiOjE3Mzg3MDQ1MjQsImp0aSI6IjQ4OTQ4MDUzMDRkZTQwNzViNzQ1NTgzZWYxMzkxOGYyIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0Ml91c2VyIn0.YuLIVN91Q3K6SBv5X7hpD1_qpOlm2twPvknS674hM_YuCFKy6BdGrzl6qyGWcdGcEAVA4SArgGJoROwQfylKpS8TP55Ju_b1HhanFjn7TQU1vxj6kHbxbJwJnx4iy6bW4wS2TXSGCvzvgTzrgKQHf09JNkIUfjwI-Trb4EdqjWZr1QjNtOL7w4608KyWimBkMTzCnEPayn26qMCI0UOyZXL6yFNXKz-nWW3SNgFp7G2auF8aRBUZF6IZ0Caef4ZardI8VYOFQKdYXujIKBW1Ff08-q33Pw3i21vAPLfNx8zH6rqAJB0ebUgYdvF7vaUmgiLOABYolRu5eZT4OMK6Iw

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="default.jpg"
Content-Type: image/jpeg

default.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW--
####
GET https://localhost:4430/api/users/test2_user/friends/
Authorization: Bearer eyJhbGciOiJSUzP1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX25hbWUiOiJhdXRoIiwiZXhwIjoxNzM4MDM3MzczLCJpYXQiOjE3Mzc5OTQxNzN9.d3051RYzd7AApiRDWzFfpKZql4FBDBFTqQmWfrE7r1UfOInDqppe4qDxreU2b-nO5veIho2jb-VP6YmxxLUrxLW8ULPNWYIl379NCRuJfcxnSHkEOqipPXLS1UU-EO1tZ3MK_8rPvGX3J_tdwXnCjNQtQqKf2S-L0apCifEvoeS_YpwPNXsgqEni0-XXT9BzLLNr-ddp8kxAWrDm_jW1_m1s6B7iS2y6SV-Pt41AEbYh5XOIA3t1ZMLdLMi2GeX6sbQffDb4fp5GLPlOwb-0v-6iVrS4Tci4POIp-a40RnlMTe_yH18IZlt7EpslnEScmbBp_zjReo6HO6AL4YVS_A

{

}
###
#check if invalid token can access protected view
GET https://localhost:4430/api/users/protected/service/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX25hbWUiOiJhdXRoIiwiZXhwIjoxNzM4MDM3MzczLCJpYXQiOjE3Mzc5OTQxNzN9.d3051RYzd7AApiRDWzFfpKZql4FBDBFTqQmWfrE7r1UfOInDqppe4qDxreU2b-nO5veIho2jb-VP6YmxxLUrxLW8ULPNWYIl379NCRuJfcxnSHkEOqipPXLS1UU-EO1tZ3MK_8rPvGX3J_tdwXnCjNQtQqKf2S-L0apCifEvoeS_YpwPNXsgqEni0-XXT9BzLLNr-ddp8kxAWrDm_jW1_m1s6B7iS2y6SV-Pt41AEbYh5XOIA3t1ZMLdLMi2GeX6sbQffDb4fp5GLPlOwb-0v-6iVrS4Tci4POIp-a40RnlMTe_yH18IZlt7EpslnEScmbBp_zjReo6HO6AL4YVS_A
###
#check if user can access protected view
GET https://localhost:4430/api/auth/protected_user/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTk3ODAzLCJpYXQiOjE3Mzc5OTI0MDMsImp0aSI6ImIyNTk0ZTNhODM0ODRhYjFhZDVkNWY5ZDcxMWQyMWUxIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0Ml91c2VyIn0.JXCGYshHfBApxbheWcMim5ifgL69pPt8zE-yDyvRKObCQW5ZIJzX__TDqwRlEyYKn2bvZvXSiNja6wlvM2O32VxMiJoeGuYSSbmdS_ZuvXmZQ20InrC2gTRp-RlmUnpsRH7e6eVGjM_Gn3mP5hCN2wPFHF57KCwpVlRI0mSzIi8CPIs6Z4SsteOAo2G7NsthRYtTbiS0LhQoyBoMGyq6pQ1pY95eJRX-jvAbhNHImN8zD2oODB33uro1lRkArDmY_nggIt3ZWOQqM7iuDhrThhi_paFvv7o3mIB1FdNK6zqErFS7UBErV0Nm0s0RSHcJLLd5hMYh_t7i3GWRVpGQUg

###
#check if bad input can access protected view
GET https://localhost:4430/api/auth/protected_user/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2OTcxNTU3LCJpYXQiOjE3MzY5NjYxNTcsImp0aSI6IjQxMzA1ZTcyNTViYjQyMTY4NDExYjkyNzljNTExZWU2IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.lnHEq4SK8S__SqOzKd4Xn88QQi82Wve5tx58YvhXZUBRkbU35bmnB_kp7525Jes36AY5sbC9YDiVZEriXNDMsy7-kAwvsSCpglKFy5mGxfOiaf8ndRiiqgySyn9B1Lbd5eWFfqesJ6aSaotwXuiwDvSh6GdNnuOtmSJTqeDXKOIU-UYPL4-sUfbxiCSygu7X7oKB27YbUvYN1r9XB6-zMoM4GBTfTYdQ_2aoK1Ch6LJYyh9-DlnGAVmJffdMA8T8cvU73xSbVowtLc-hfHGe8hpXPtmuMDHLclLTK07L5s2HwV82jrICaTpjXOjVJ7lR7saRQ9F8enxQLC9S9ZlDow

###
#check if invalid token can access protected view
GET https://localhost:4430/api/game/protected/user/
Authorization: Bearer iyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2OTY5NDE2LCJpYXQiOjE3MzY5NjQwMTYsImp0aSI6ImVjY2Q2MmFmMTY5ZDRlY2FhMzllOGE4NWRlZDVkODc4IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.OzlT1gv0YQby-SdXYgyCO-PP53V0Vd97uoTlnWDZFvhcpItz9PsgZmVXT48mIZZ-nrITSruIqKgLNAyukDTiU1ZQTyZggqE9nrvvFzPs1s_c1SsdBBV9SHvRd13b7L7cO1KXSN_iZA5Dg9AsfdzHtIfPK2E2a-pLj9Yv-0bk8kBiWvYz8WkFUSz9wcMg0eMy-6S9-P0nM9OYXi3eLvlWkOJ3YE-bW8T-JbVgaUncMXmWEB8W5YfJsVuqx1tRMU20724ylRrugVFICzlmc3x0XqZ-UjVpVWeytLUwSSj3lmXHylhXFzRllu0FN0lN4B9AsrQHDvmghnk1AxKcJ1e8nA

###
#get 
GET https://localhost:4430/api/auth/test_user/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2OTcyMTc4LCJpYXQiOjE3MzY5NjY3NzgsImp0aSI6IjEwZGYwZTNiODUyZDQ0ZTk5MTc1YzczOTQ4NDdkNGY4IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.ClBkyJUt94p8eoKVXznIlpJrJgOMH08p4z4gyEwCytqw4J_h3Rir1NB0k_gAjrldK9uhSXIHK-psiJMde9Gf5C9J-5FUB4-eXxu7bC6GtQMDITz6_nmoaOLRDEk8gdj8FPvnTbs25uFebkwFvo2Rbuls7B6BhKr-dTbFAtFMh5dsaK2m7sL3J1ez3X6IbyCb_lqfqKr5vqmQZzxuAGrIY8oAWnZiR3K5aOLyHStbX-K7LM3cDMefOognvbTgb51gmwXtnVY-QBxvhuAujYwPUOD9bVUco22LjmLziakggoV765uORJhke1q4mCMSXONRqB-GVz6znpBgioAgn_nBtQ
###

DELETE  https://localhost:4430/api/auth/delete/test_user/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2OTcxOTQzLCJpYXQiOjE3MzY5NjY1NDMsImp0aSI6ImE4NDY5OWE0NTA3NzRjMjJhNWYyZmRlN2ZiNmYzYWI5IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.WJMnZqPg1uZjSxYDYfzw0MkKriPr9UFcr2uidHaRQkUdu-P_iapWnaRTnHFcJoeRJkCMpsvCBkEP5CCGmMnSQv_y0STxysUFtIqz8kLsxW3uZfVxOJcqKch90jmglccJKv0Xe0Qs8mQzKhtL-5RSgHDXILenU0lOd11kS9aHxwMZIUXOVWEYkBgyQqI7g0SdLaVUQ_6e4rwoEs5F4Qg6c9TxRYpdOILcI7YLY1K_3esgbyj1L3g6YUFvc2ADbc9cfqfyVdCYTE0-qa9QIlT58zuF72Wg5UBhixDBfhLeGLXX6XmKJzyopdYm2_hzUl5WtY7GtW4pCvv5t4ZKsVVKug
###

POST https://localhost:4430/api/auth/logout/
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczODI1NTY2My4yMDk2NTQsImlhdCI6MTczODE2OTI2MywianRpIjoiZDFiZjM0MWZlZjI3NDU0OTg1MDc4M2Q3MzhlNjAxZDgiLCJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6InRlc3QyX3VzZXIifQ.8PJkFpcL4BOrUi9dDBDJY40dFxXoIgpba_vdRha4ua9oQcm0RJxL9O537nqoesqb-ohEBsJHiCKyn3eQkyQBcVvNBqAYGkglJ7Tv3uz5OjoQ6foIrXy_XM2lGokay43rK-QcabOWri0xRlVgV3VEy99Dy8DtjyNzlLtjCPqLOglpx2QMpj7cj6s0ECY0E4wUb7scrzkRA0M1omDd-E11kEhI0kEE5Kb48k0AaMYwA9QdS6TRs2bh9xNCRjyG-ZRuQ0pnR7prSVPTqHNNx19TFIVmlNvW1gg_8Vds14Gi4VVCOrb1WTGaXd_-Uiy2Vvk5XNKCLHI_qmLlm0hTdzNtFQ"
}

###


POST https://localhost:4430/api/auth/2fa/setup/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4MTc4MTIwLCJpYXQiOjE3MzgxNzI3MjAsImp0aSI6IjM5NDM3YTlmN2EwYzRkYjRhNjE4OWI2ZTQ5OTg2MWRkIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0Ml91c2VyIn0.bpEYaPrEVAYpCqu5cZ_GN5aeTdpyHXeh8Os9YPTOgPsgl4yYYKRIz1ljvRj7SfRx7zJ6tlM6J1ACaalEYRWcNp-fF7KBzdN0hkkiAHp-fZRWfhYy1BTc-UVF5Y_FyGnRQ19SF1tczV6seTcSb5T9Q2yAtmOIcJEDTYEtCWIf1hqzia-cCmGEQTei2KGM4LZUjXm0WRhnzUxvcOZQAUXv9fzAZcJKTBaSPD5fu1ZO6xzCmexlDwuv-fTvnSu-nsSWWo11oa6xqng5hCW7852J6CEsH2W8eVeoGXgAEnIzJuIb8IqrbA7WpL0vB9XlUtYbn53af6ivmDx1pvdsSkOfKg
Content-Type: application/json

{
  "enable": false
}