
#add user to db
POST https://localhost:4430/api/auth/signup/
Content-Type: application/json

{
  "username": "test_user",
  "password": "pass123456",
  "email": "test_user@gmail.com"
}
###
#get user token
POST https://localhost:4430/api/auth/token/
Content-Type: application/json

{
  "username": "test_user",
  "password": "pass123456"
}
###
#get service token
POST https://localhost:4430/api/auth/service-token/
Content-Type: application/json

{
  "service_name": "auth",
  "password": "private"
}


###
#check if service can access protected view
GET https://localhost:4430/api/auth/protected_service/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX25hbWUiOiJhdXRoIiwiZXhwIjoxNzM2NDc0NzkxLCJpYXQiOjE3MzY0MzE1OTF9.JJIFREqbjBccM8o0RufmrdmbOg_Tro6e5nCAFWABR--3kMMFVitoezZMSwkWehwcrOytyIwJk5UG51ar8l9JZw7fa75HHrVBFwuBmD2yRt0Gl_sRoryUnNm7qn5LIvf95m1qdUF32Z4b70il1F1aKmNUGPvB8i3P0jhKgEda0iDrWnZ3XK6JgFLHhMMVC1fnQNxEvmNSu6FCDu6ZX81xFuhW1MQpPpZao8a5xuZ91cZuR35pUVe-NgDc-eMWm4fgY-sSwSV0HKDG4414he3Z9YtIG0tmLKBFTHzEUrUepAwxBXqViD89KbsUYK095nZ7cA8z7o7na7lZ9N4OejzlHw

###
#check if bad input can access protected view
GET https://localhost:4430/api/auth/protected_service/


###
#check if invalid token can access protected view
GET https://localhost:4430/api/auth/protected_service/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX25hbWUiOiJhdXRoIiwiZXhwIjoxNzM2NDg1MTE2LCJpYXQiOjE3MzY0NDE5MTZ9.jb9FBYVMEb54SjGg8Maawd6Erg8i5CGHNqhHX1vMIJhT43Mg8xflnaLFyzxsMLqwBD9Y07TNZzts9YplPTMrK8rvfbBm6pKLk61JP_biwQtot8Cqe_D4CpH-VCxEHXuHrMoMsf6KXOSCWrLqz_VfAogIO2fk8n9ZdmjQxc_4H6so0buiH574VgPg-Mq3QFODvrN7ESdA_YRY7mZ0CU1AnRYOedM3MN0iREy-F1ZwQV72wZZQmfUSys-bHtqstc121VYRH-cXuoNjvcIN41rBGSekPXk3EoCayqi13ymXe1hrAEQPnukaFZyyJLbo4Egt79r-rkeR2QJS07sAt8t5zA


###
#check if user can access protected view
GET https://localhost:4430/api/auth/protected_user/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2NzkwNDk1LCJpYXQiOjE3MzY3ODUwOTUsImp0aSI6IjFmYTc1Y2UyYmFmMTQ0NWZiMmMzNmQ5MjdmYTMxZWQ2IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.SS_tEjo0lPNaPZiFMDQbeFn9UKlZtgCpwuXm0XUQfgLmMLXcBs11CFNES-RhEw98aVHuZThhA0S0LPfiVRS-COB7sg_BKd6knnbbhHxT1i1hcbf1XwpvhV8bjMx8T3ZKM5wdCoonf9UBb7bDF492u_Zg4ALDIgZY0KnCaxuTnLzE6Q8o6mDBo6wO_yA7WF09jmh1l_AnITcpacilSv-PI1ZMWgQh1-JLiAClFBwv_Eu2IUSMigDdHQFhIPLClkq44CQs6FBlFpl6rJQKdidtTw0zoISamyGBbG9SsgPNjTJMaf_xz4XEsZX1K_bY6crs1XBEYehOlh2K-960PfTQTQ
###
#check if bad input can access protected view
GET https://localhost:4430/api/auth/protected_user/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2NzkwODYwLCJpYXQiOjE3MzY3ODU0NjAsImp0aSI6IjdhMjM4Y2ViYWMxMTRhZDU4OTVjNDljMzcxMGMxMjhiIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.MQPu4F9i-Zvh3toZr42mi0Gy1UstEXfSo4shijmgOgLbrhEvQaMnvOgEiAp4V_91rpqZ2FFgQX6haWgI0YbNvgR9Ki_uj0k-YqHoEzLA9eAhtPkoQ-2dZBWeJubOSqDPiJUptIbq2uNADy47lChTAE6ee6xuKhcbeVxD-CWtgNmcSeWNTGVezf7e3MvvkHh00VBnKuOJd-N7PTmWfHfVC7FJcoJziuRiurQKB8f7HCVHqxt3WvDfV2VcDRWEsQxzohfnAW7d9sn_brNJJf1Zi83Q0SgNruNAXI9kylj6wqUC4SnpMsChGg562kh1Qr97hdlMejtKuNPNOjtziUgn3Q

###
#check if invalid token can access protected view
GET https://localhost:4430/api/auth/protected_user/
Authorization: Bearer <invaliduser token>

###
#get 
GET https://localhost:4430/api/auth/test_user/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2NzkwOTA1LCJpYXQiOjE3MzY3ODU1MDUsImp0aSI6IjA4ZmFlZTBkZTI4NzRkN2VhOWY0Mjg2ODhiMTU2MDc1IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.qcikwK3981NWdXDE7B20DTlan8sILOnH77h0OfQlDK7fSWmvcL5GGpR6N8LT2ow2H9XHDaDYJ3rVd0K7skOZGO0p6ejMnl1Yx64koHNCWVOKFpn8Rbvj8x6RmUeiSGNBmdBUPQowpcUpNG3PW-cyvRnWnqf4VOOVqt4RgNTJfynMSMU0jllYvS1BvWkw27awcFdjIYxGQlmTeCjRDnlQiyaZ6Y_u2uYX49DRcmq-uXZn3eQuvpYr0BLuq2ectxCDpDc8C6QN1MQyDmhHzQp47ntgH-cZSExUkDE9y1GPUDvzQ66y0vmVyXYZaqKBMJDiycm8wE1EbFMj7Ne7Q_IHEw
###

DELETE  https://localhost:4430/api/auth/delete/test_user/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2NDUyMDU0LCJpYXQiOjE3MzY0NDY2NTQsImp0aSI6IjFlY2EwNzQyYTRmMDRiZmJiYTEzZjMxODU4ZWQxNTY0IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.YJ279K-Jtl2sGqmfq721ItJnwD5D-DN72eJlMLzBEcxrebv8QLajKh7ZxxtkV4pwg7mwLdKjirzuAbyRQ4BhJpiH777tE4VWvn4Ro5ZRfrGQWX-kWriAl0X1bviwqB0Md4XgtqEc4hnPGEN8AkMRWujSERVb8nFesHhzK3nMHJAd_sEPWd8NqgADWHuzSj3TXKlL9XkXZ7boq3gRpPqPafQoeYXFw9w54_olAMrRuUSv_JHbgLU2mqti-tTtZ6iRUiFWLNf0IirwperIf4iOgjNlawhFgbH7oHCJBaNwVpV8uayZezZIICAYGA6e4eJ1WrWJ7F_GWr6hfoIJSwFfKw

###

GET https://localhost:4430/api/game/protected/user/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2NzkzNDk5LCJpYXQiOjE3MzY3ODgwOTksImp0aSI6IjY4MmZkZTE0OGNlYzRhMDNhOTEwM2FmM2U4MzkzYWI4IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.an5EoIwywQbyoVwMWI1HCwW_xygfe8_aljsvEalwW5Rnu7lW31gKteAyrdpQ-oL-bWvQOH4j-5bG_kQno7Xc8-T-nQ4A50_E_4ePk1bv-nBCs7WGFU3S56XWXMnQUzDa0puN9uMOga28TIsUn7qj9HRouXbSGRUmQcJffLtrKrRI_KZaGXA0tfrBv8NnJp7VnVPpn7jF_Clmvci3avVKqdu_ji0RfoABqavahraJfZ27RJGLf_sMsWreHK2ZDv8IgxSS9c9IRRwILSqc5iYo267dRrRveCCGNzZgPgoMZpw2xjGGcD3a1Ynb1kAR7U_zrdt0j1LlI2HlahVmVNfbNQ