################################################################
#                                                              #
#                       Create user                            #
#                                                              #
################################################################

#create user1
post https://localhost:4430/api/auth/signup/
Content-Type: application/json

{
  "username": "bidon",
  "password": "Pass12456!",
  "email": "d@gmail.com"
}
###

#create user2
post https://localhost:4430/api/auth/signup/
Content-Type: application/json

{
  "username": "tkt",
  "password": "Pass12456!",
  "email": "oui@gmail.com"
}
###

#create user3
post https://localhost:4430/api/auth/signup/
Content-Type: application/json

{
  "username": "test",
  "password": "Pass12456!",
  "email": "non@gmail.com"
}
###

#get user1 token
POST https://localhost:4430/api/auth/token/
Content-Type: application/json

{
  "username": "bidon",
  "password": "Pass12456!"
}
###

#get user2 token
POST https://localhost:4430/api/auth/token/
Content-Type: application/json

{
  "username": "tkt",
  "password": "Pass12456!"
}
###

#get user3 token
POST https://localhost:4430/api/auth/token/
Content-Type: application/json

{
  "username": "test",
  "password": "Pass12456!"
}
###

#check if tournament service is working
GET https://localhost:4430/api/tournament/test/
###
################################################################
#                                                              #
#                       Tournament tests                       #
#                                                              #
################################################################

# ************************** POST ************************** #

#create tournament
POST https://localhost:4430/api/tournament/create_tournament/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwNzUzNjc3LCJpYXQiOjE3NDA3NDgyNzcsImp0aSI6ImIzZjIwNjVlOGZmMjQ2ZGZiMzQ3ODY3YWMxYmMzNDYyIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJiaWRvbiJ9.Rzhua2jaLweoPQ2SQ6e2uqOifixJXdjZorqeX_HwdtxDY5i85UbVwnGM-FNDyMdkm3lubet7yEEddLDGmJptrDNPc6-TQYMgYlIG2fpaYUe-UErYF0IKQgvDe6ZP5cOvw8ADjQg5B_dZdH58tyB0CYXEc9zraK513cq6XEP8qIXrJWPQR3De1RJw5TFmB0oTJ_quY68ejGfxH1doepYeNc1tYeXGHiQMkJ373dDoAF_QRwatWmdP8oh775Y0U6k4UEUrvQRNC9ZVxG4r_ZSRxxEjlF7SlEsVwkA35PXGGRmunh66EsJH41Gef-AO0VeJjRR-DtBc5JLdyOiutS8qpQ
Content-Type: application/json

{
    "name": "chokbar de bz",
    "max_users": 3
}
###

#join tournament
POST https://localhost:4430/api/tournament/join/ab58126c-0f3a-4915-8e42-fce155e8fa93/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwNzUzODIyLCJpYXQiOjE3NDA3NDg0MjIsImp0aSI6ImM2ZDc5OWYxMGU0NTQ1ZmJiZmIxYjliMzY3ODFhOTBjIiwidXNlcl9pZCI6MiwidXNlcm5hbWUiOiJ0a3QifQ.fKjaRaAkisNnC8QY_13tLlhn5_zrNdS-NUQkEsW3ng_sTpuwBiHxSjxVX7AUPxIozDnGjEh29WLOjuTDx-exXkbLwAKkD0ylIfCf-Nq0LboZvCpF05xmxN0-QGzRrBhweTz0KeVotqzH2XxFGifLzdAa9KJlPdSxqCozx6M0pGssRvejrND_cDFC4URkrpNZqJKWs4fkzBYGJyaFtLk7Rcjyz_QU2bIu1qIrofYiByxwydhITtE1DiVEtrZ_8AJ3cUj_LmwiCKZLKaJrIiSUcUWudvqhWPRzy_iurG6SHt0ZExaphgr7UXPYVagkfnLffhd-Byw23ko4LCjnXkyu-g
Content-Type: application/json

###

#leave tournament
POST https://localhost:4430/api/tournament/leave/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwNzUzNjc3LCJpYXQiOjE3NDA3NDgyNzcsImp0aSI6ImIzZjIwNjVlOGZmMjQ2ZGZiMzQ3ODY3YWMxYmMzNDYyIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJiaWRvbiJ9.Rzhua2jaLweoPQ2SQ6e2uqOifixJXdjZorqeX_HwdtxDY5i85UbVwnGM-FNDyMdkm3lubet7yEEddLDGmJptrDNPc6-TQYMgYlIG2fpaYUe-UErYF0IKQgvDe6ZP5cOvw8ADjQg5B_dZdH58tyB0CYXEc9zraK513cq6XEP8qIXrJWPQR3De1RJw5TFmB0oTJ_quY68ejGfxH1doepYeNc1tYeXGHiQMkJ373dDoAF_QRwatWmdP8oh775Y0U6k4UEUrvQRNC9ZVxG4r_ZSRxxEjlF7SlEsVwkA35PXGGRmunh66EsJH41Gef-AO0VeJjRR-DtBc5JLdyOiutS8qpQ
Content-Type: application/json

###

#launch tournament
POST https://localhost:4430/api/tournament/launch/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwNzUzNjc3LCJpYXQiOjE3NDA3NDgyNzcsImp0aSI6ImIzZjIwNjVlOGZmMjQ2ZGZiMzQ3ODY3YWMxYmMzNDYyIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJiaWRvbiJ9.Rzhua2jaLweoPQ2SQ6e2uqOifixJXdjZorqeX_HwdtxDY5i85UbVwnGM-FNDyMdkm3lubet7yEEddLDGmJptrDNPc6-TQYMgYlIG2fpaYUe-UErYF0IKQgvDe6ZP5cOvw8ADjQg5B_dZdH58tyB0CYXEc9zraK513cq6XEP8qIXrJWPQR3De1RJw5TFmB0oTJ_quY68ejGfxH1doepYeNc1tYeXGHiQMkJ373dDoAF_QRwatWmdP8oh775Y0U6k4UEUrvQRNC9ZVxG4r_ZSRxxEjlF7SlEsVwkA35PXGGRmunh66EsJH41Gef-AO0VeJjRR-DtBc5JLdyOiutS8qpQ

###

# *************************** DELETE *************************** #

#delete tournament
DELETE https://localhost:4430/api/tournament/delete_tournament/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwNzUzNjc3LCJpYXQiOjE3NDA3NDgyNzcsImp0aSI6ImIzZjIwNjVlOGZmMjQ2ZGZiMzQ3ODY3YWMxYmMzNDYyIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJiaWRvbiJ9.Rzhua2jaLweoPQ2SQ6e2uqOifixJXdjZorqeX_HwdtxDY5i85UbVwnGM-FNDyMdkm3lubet7yEEddLDGmJptrDNPc6-TQYMgYlIG2fpaYUe-UErYF0IKQgvDe6ZP5cOvw8ADjQg5B_dZdH58tyB0CYXEc9zraK513cq6XEP8qIXrJWPQR3De1RJw5TFmB0oTJ_quY68ejGfxH1doepYeNc1tYeXGHiQMkJ373dDoAF_QRwatWmdP8oh775Y0U6k4UEUrvQRNC9ZVxG4r_ZSRxxEjlF7SlEsVwkA35PXGGRmunh66EsJH41Gef-AO0VeJjRR-DtBc5JLdyOiutS8qpQ
###

# *************************** READ *************************** #

#detail tournament
GET https://localhost:4430/api/tournament/detail/5e39a0a3-7506-45e1-8d4e-d56cf9142a2f/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwNzUzNjc3LCJpYXQiOjE3NDA3NDgyNzcsImp0aSI6ImIzZjIwNjVlOGZmMjQ2ZGZiMzQ3ODY3YWMxYmMzNDYyIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJiaWRvbiJ9.Rzhua2jaLweoPQ2SQ6e2uqOifixJXdjZorqeX_HwdtxDY5i85UbVwnGM-FNDyMdkm3lubet7yEEddLDGmJptrDNPc6-TQYMgYlIG2fpaYUe-UErYF0IKQgvDe6ZP5cOvw8ADjQg5B_dZdH58tyB0CYXEc9zraK513cq6XEP8qIXrJWPQR3De1RJw5TFmB0oTJ_quY68ejGfxH1doepYeNc1tYeXGHiQMkJ373dDoAF_QRwatWmdP8oh775Y0U6k4UEUrvQRNC9ZVxG4r_ZSRxxEjlF7SlEsVwkA35PXGGRmunh66EsJH41Gef-AO0VeJjRR-DtBc5JLdyOiutS8qpQ

###

#list all tournament
GET https://localhost:4430/api/tournament/list/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwNzUzNjc3LCJpYXQiOjE3NDA3NDgyNzcsImp0aSI6ImIzZjIwNjVlOGZmMjQ2ZGZiMzQ3ODY3YWMxYmMzNDYyIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJiaWRvbiJ9.Rzhua2jaLweoPQ2SQ6e2uqOifixJXdjZorqeX_HwdtxDY5i85UbVwnGM-FNDyMdkm3lubet7yEEddLDGmJptrDNPc6-TQYMgYlIG2fpaYUe-UErYF0IKQgvDe6ZP5cOvw8ADjQg5B_dZdH58tyB0CYXEc9zraK513cq6XEP8qIXrJWPQR3De1RJw5TFmB0oTJ_quY68ejGfxH1doepYeNc1tYeXGHiQMkJ373dDoAF_QRwatWmdP8oh775Y0U6k4UEUrvQRNC9ZVxG4r_ZSRxxEjlF7SlEsVwkA35PXGGRmunh66EsJH41Gef-AO0VeJjRR-DtBc5JLdyOiutS8qpQ

###

#list my rooms
GET https://localhost:4430/api/tournament/list_my_rooms/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwNzUzNjc3LCJpYXQiOjE3NDA3NDgyNzcsImp0aSI6ImIzZjIwNjVlOGZmMjQ2ZGZiMzQ3ODY3YWMxYmMzNDYyIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJiaWRvbiJ9.Rzhua2jaLweoPQ2SQ6e2uqOifixJXdjZorqeX_HwdtxDY5i85UbVwnGM-FNDyMdkm3lubet7yEEddLDGmJptrDNPc6-TQYMgYlIG2fpaYUe-UErYF0IKQgvDe6ZP5cOvw8ADjQg5B_dZdH58tyB0CYXEc9zraK513cq6XEP8qIXrJWPQR3De1RJw5TFmB0oTJ_quY68ejGfxH1doepYeNc1tYeXGHiQMkJ373dDoAF_QRwatWmdP8oh775Y0U6k4UEUrvQRNC9ZVxG4r_ZSRxxEjlF7SlEsVwkA35PXGGRmunh66EsJH41Gef-AO0VeJjRR-DtBc5JLdyOiutS8qpQ

###

#list rooms pool
GET https://localhost:4430/api/tournament/list_rooms_pool/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwNzUzNjc3LCJpYXQiOjE3NDA3NDgyNzcsImp0aSI6ImIzZjIwNjVlOGZmMjQ2ZGZiMzQ3ODY3YWMxYmMzNDYyIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJiaWRvbiJ9.Rzhua2jaLweoPQ2SQ6e2uqOifixJXdjZorqeX_HwdtxDY5i85UbVwnGM-FNDyMdkm3lubet7yEEddLDGmJptrDNPc6-TQYMgYlIG2fpaYUe-UErYF0IKQgvDe6ZP5cOvw8ADjQg5B_dZdH58tyB0CYXEc9zraK513cq6XEP8qIXrJWPQR3De1RJw5TFmB0oTJ_quY68ejGfxH1doepYeNc1tYeXGHiQMkJ373dDoAF_QRwatWmdP8oh775Y0U6k4UEUrvQRNC9ZVxG4r_ZSRxxEjlF7SlEsVwkA35PXGGRmunh66EsJH41Gef-AO0VeJjRR-DtBc5JLdyOiutS8qpQ

###

#list pools
GET https://localhost:4430/api/tournament/list_pools/ab58126c-0f3a-4915-8e42-fce155e8fa93/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwNzUzNjc3LCJpYXQiOjE3NDA3NDgyNzcsImp0aSI6ImIzZjIwNjVlOGZmMjQ2ZGZiMzQ3ODY3YWMxYmMzNDYyIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJiaWRvbiJ9.Rzhua2jaLweoPQ2SQ6e2uqOifixJXdjZorqeX_HwdtxDY5i85UbVwnGM-FNDyMdkm3lubet7yEEddLDGmJptrDNPc6-TQYMgYlIG2fpaYUe-UErYF0IKQgvDe6ZP5cOvw8ADjQg5B_dZdH58tyB0CYXEc9zraK513cq6XEP8qIXrJWPQR3De1RJw5TFmB0oTJ_quY68ejGfxH1doepYeNc1tYeXGHiQMkJ373dDoAF_QRwatWmdP8oh775Y0U6k4UEUrvQRNC9ZVxG4r_ZSRxxEjlF7SlEsVwkA35PXGGRmunh66EsJH41Gef-AO0VeJjRR-DtBc5JLdyOiutS8qpQ

###