################################################################
#                                                              #
#                       Create user                            #
#                                                              #
################################################################

#create user1
post https://localhost:4430/api/auth/signup/
Content-Type: application/json

{
  "username": "bidon",
  "password": "Pass12456!",
  "email": "d@gmail.com"
}
###

#create user2
post https://localhost:4430/api/auth/signup/
Content-Type: application/json

{
  "username": "tkt",
  "password": "Pass12456!",
  "email": "oui@gmail.com"
}
###

#create user3
post https://localhost:4430/api/auth/signup/
Content-Type: application/json

{
  "username": "test",
  "password": "Pass12456!",
  "email": "non@gmail.com"
}
###

#get user1 token
POST https://localhost:4430/api/auth/token/
Content-Type: application/json

{
  "username": "bidon",
  "password": "Pass12456!"
}
###

#get user2 token
POST https://localhost:4430/api/auth/token/
Content-Type: application/json

{
  "username": "tkt",
  "password": "Pass12456!"
}
###

#get user3 token
POST https://localhost:4430/api/auth/token/
Content-Type: application/json

{
  "username": "test",
  "password": "Pass12456!"
}
###

#check if tournament service is working
GET https://localhost:4430/api/tournament/test/
###
################################################################
#                                                              #
#                       Tournament tests                       #
#                                                              #
################################################################

# ************************** POST ************************** #

#create tournament
POST https://localhost:4430/api/tournament/create_tournament/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwOTM0Njc1LCJpYXQiOjE3NDA5MjkyNzUsImp0aSI6IjIxNzUxNDQwOGZlYjQ1Njg5NDcwYzdiNGIxZGNmZjg0IiwidXNlcl9pZCI6MiwidXNlcm5hbWUiOiJ0a3QifQ.IFF0kRFlu-pSK8F_1ifiFwT6LQsO6M-Ig88c12T6KkOnltTA9-aNh0v1C8H4PWMeKsB_0E5KwHJGVuwZwv1z0x3F2nvSvlT65f4dmxKDXghGJWgNiPLMwDxtp_gI2VMfIwUBD1gprC_do9I2VWV3fIavOJuZ_jfeAIcg2-aAea9FIBN128Wmo3bgkIGNkMHHp_tNvQ0DSSFxCB7gCE7WklfRA_NrmbT_slEPnzq9u_zfMtoDS0JUeOyrXSPXHOcBYdEYd9ksg75vYVKAYFo7ru7Mt0JKyfjD1YJlhMzxquDhDG-Hp-cEWKBagQick6BNKKSDRUomkH14iyhl-pXFAw
Content-Type: application/json

{
    "name": "chokbarr de bz",
    "max_users": 3
}
###

#join tournament
POST https://localhost:4430/api/tournament/join/e1361f51-cf6f-4bcc-b098-ad0e8ddc4b57/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwOTM0NjUzLCJpYXQiOjE3NDA5MjkyNTMsImp0aSI6ImM3NGE2NDI1Zjg1MjQxMzJhZDY5NWMxODJiY2U0MDMzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJiaWRvbiJ9.WVabbnv6zDlTNAtaIUcnVHSstOoatPjejWI4DGOwJPJ1gpDBm2znZpc68iYDR81mGSt6qlU9DEYrWo-acJYQwu7Dob97A4yT7TOZjHV_W5RxmuEohRaulobxsEcmpUnRNMEs9nx0IYenjhSiBzi6Q66JCxkSR1RrP84pm4vD3PYlvaYwsUHvBpKUDTxUvFCJxX0DfE4eHombGh4oJBBaItyMZYsj8X7xqTitBQ-zfDZEoEWS10HufjmdmcsrQ2lzPTOINiJoYp3nLz5Vv_MgaXaiKluxaDw-o2aMhE6myvU_Gx_UzavmGUcX3fazdqbAw1eg5SvBtCV_o9jePEJsQA
Content-Type: application/json

###

#leave tournament
POST https://localhost:4430/api/tournament/leave/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwOTM0NjUzLCJpYXQiOjE3NDA5MjkyNTMsImp0aSI6ImM3NGE2NDI1Zjg1MjQxMzJhZDY5NWMxODJiY2U0MDMzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJiaWRvbiJ9.WVabbnv6zDlTNAtaIUcnVHSstOoatPjejWI4DGOwJPJ1gpDBm2znZpc68iYDR81mGSt6qlU9DEYrWo-acJYQwu7Dob97A4yT7TOZjHV_W5RxmuEohRaulobxsEcmpUnRNMEs9nx0IYenjhSiBzi6Q66JCxkSR1RrP84pm4vD3PYlvaYwsUHvBpKUDTxUvFCJxX0DfE4eHombGh4oJBBaItyMZYsj8X7xqTitBQ-zfDZEoEWS10HufjmdmcsrQ2lzPTOINiJoYp3nLz5Vv_MgaXaiKluxaDw-o2aMhE6myvU_Gx_UzavmGUcX3fazdqbAw1eg5SvBtCV_o9jePEJsQA
Content-Type: application/json

###

#launch tournament
POST https://localhost:4430/api/tournament/launch/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwOTM0NjUzLCJpYXQiOjE3NDA5MjkyNTMsImp0aSI6ImM3NGE2NDI1Zjg1MjQxMzJhZDY5NWMxODJiY2U0MDMzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJiaWRvbiJ9.WVabbnv6zDlTNAtaIUcnVHSstOoatPjejWI4DGOwJPJ1gpDBm2znZpc68iYDR81mGSt6qlU9DEYrWo-acJYQwu7Dob97A4yT7TOZjHV_W5RxmuEohRaulobxsEcmpUnRNMEs9nx0IYenjhSiBzi6Q66JCxkSR1RrP84pm4vD3PYlvaYwsUHvBpKUDTxUvFCJxX0DfE4eHombGh4oJBBaItyMZYsj8X7xqTitBQ-zfDZEoEWS10HufjmdmcsrQ2lzPTOINiJoYp3nLz5Vv_MgaXaiKluxaDw-o2aMhE6myvU_Gx_UzavmGUcX3fazdqbAw1eg5SvBtCV_o9jePEJsQA

###

# *************************** DELETE *************************** #

#delete tournament
DELETE https://localhost:4430/api/tournament/delete_tournament/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwOTM0NjUzLCJpYXQiOjE3NDA5MjkyNTMsImp0aSI6ImM3NGE2NDI1Zjg1MjQxMzJhZDY5NWMxODJiY2U0MDMzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJiaWRvbiJ9.WVabbnv6zDlTNAtaIUcnVHSstOoatPjejWI4DGOwJPJ1gpDBm2znZpc68iYDR81mGSt6qlU9DEYrWo-acJYQwu7Dob97A4yT7TOZjHV_W5RxmuEohRaulobxsEcmpUnRNMEs9nx0IYenjhSiBzi6Q66JCxkSR1RrP84pm4vD3PYlvaYwsUHvBpKUDTxUvFCJxX0DfE4eHombGh4oJBBaItyMZYsj8X7xqTitBQ-zfDZEoEWS10HufjmdmcsrQ2lzPTOINiJoYp3nLz5Vv_MgaXaiKluxaDw-o2aMhE6myvU_Gx_UzavmGUcX3fazdqbAw1eg5SvBtCV_o9jePEJsQA
###

# *************************** READ *************************** #

#detail tournament
GET https://localhost:4430/api/tournament/detail/5e39a0a3-7506-45e1-8d4e-d56cf9142a2f/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwOTM0NjUzLCJpYXQiOjE3NDA5MjkyNTMsImp0aSI6ImM3NGE2NDI1Zjg1MjQxMzJhZDY5NWMxODJiY2U0MDMzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJiaWRvbiJ9.WVabbnv6zDlTNAtaIUcnVHSstOoatPjejWI4DGOwJPJ1gpDBm2znZpc68iYDR81mGSt6qlU9DEYrWo-acJYQwu7Dob97A4yT7TOZjHV_W5RxmuEohRaulobxsEcmpUnRNMEs9nx0IYenjhSiBzi6Q66JCxkSR1RrP84pm4vD3PYlvaYwsUHvBpKUDTxUvFCJxX0DfE4eHombGh4oJBBaItyMZYsj8X7xqTitBQ-zfDZEoEWS10HufjmdmcsrQ2lzPTOINiJoYp3nLz5Vv_MgaXaiKluxaDw-o2aMhE6myvU_Gx_UzavmGUcX3fazdqbAw1eg5SvBtCV_o9jePEJsQA

###

#list all tournament
GET https://localhost:4430/api/tournament/list/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwOTM0NjUzLCJpYXQiOjE3NDA5MjkyNTMsImp0aSI6ImM3NGE2NDI1Zjg1MjQxMzJhZDY5NWMxODJiY2U0MDMzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJiaWRvbiJ9.WVabbnv6zDlTNAtaIUcnVHSstOoatPjejWI4DGOwJPJ1gpDBm2znZpc68iYDR81mGSt6qlU9DEYrWo-acJYQwu7Dob97A4yT7TOZjHV_W5RxmuEohRaulobxsEcmpUnRNMEs9nx0IYenjhSiBzi6Q66JCxkSR1RrP84pm4vD3PYlvaYwsUHvBpKUDTxUvFCJxX0DfE4eHombGh4oJBBaItyMZYsj8X7xqTitBQ-zfDZEoEWS10HufjmdmcsrQ2lzPTOINiJoYp3nLz5Vv_MgaXaiKluxaDw-o2aMhE6myvU_Gx_UzavmGUcX3fazdqbAw1eg5SvBtCV_o9jePEJsQA

###

#list my rooms
GET https://localhost:4430/api/tournament/list_my_rooms/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwOTM0NjUzLCJpYXQiOjE3NDA5MjkyNTMsImp0aSI6ImM3NGE2NDI1Zjg1MjQxMzJhZDY5NWMxODJiY2U0MDMzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJiaWRvbiJ9.WVabbnv6zDlTNAtaIUcnVHSstOoatPjejWI4DGOwJPJ1gpDBm2znZpc68iYDR81mGSt6qlU9DEYrWo-acJYQwu7Dob97A4yT7TOZjHV_W5RxmuEohRaulobxsEcmpUnRNMEs9nx0IYenjhSiBzi6Q66JCxkSR1RrP84pm4vD3PYlvaYwsUHvBpKUDTxUvFCJxX0DfE4eHombGh4oJBBaItyMZYsj8X7xqTitBQ-zfDZEoEWS10HufjmdmcsrQ2lzPTOINiJoYp3nLz5Vv_MgaXaiKluxaDw-o2aMhE6myvU_Gx_UzavmGUcX3fazdqbAw1eg5SvBtCV_o9jePEJsQA

###

#list rooms pool
GET https://localhost:4430/api/tournament/list_rooms_pool/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwOTM0NjUzLCJpYXQiOjE3NDA5MjkyNTMsImp0aSI6ImM3NGE2NDI1Zjg1MjQxMzJhZDY5NWMxODJiY2U0MDMzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJiaWRvbiJ9.WVabbnv6zDlTNAtaIUcnVHSstOoatPjejWI4DGOwJPJ1gpDBm2znZpc68iYDR81mGSt6qlU9DEYrWo-acJYQwu7Dob97A4yT7TOZjHV_W5RxmuEohRaulobxsEcmpUnRNMEs9nx0IYenjhSiBzi6Q66JCxkSR1RrP84pm4vD3PYlvaYwsUHvBpKUDTxUvFCJxX0DfE4eHombGh4oJBBaItyMZYsj8X7xqTitBQ-zfDZEoEWS10HufjmdmcsrQ2lzPTOINiJoYp3nLz5Vv_MgaXaiKluxaDw-o2aMhE6myvU_Gx_UzavmGUcX3fazdqbAw1eg5SvBtCV_o9jePEJsQA

###

#list pools
GET https://localhost:4430/api/tournament/list_pools/ab58126c-0f3a-4915-8e42-fce155e8fa93/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwOTM0NjUzLCJpYXQiOjE3NDA5MjkyNTMsImp0aSI6ImM3NGE2NDI1Zjg1MjQxMzJhZDY5NWMxODJiY2U0MDMzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJiaWRvbiJ9.WVabbnv6zDlTNAtaIUcnVHSstOoatPjejWI4DGOwJPJ1gpDBm2znZpc68iYDR81mGSt6qlU9DEYrWo-acJYQwu7Dob97A4yT7TOZjHV_W5RxmuEohRaulobxsEcmpUnRNMEs9nx0IYenjhSiBzi6Q66JCxkSR1RrP84pm4vD3PYlvaYwsUHvBpKUDTxUvFCJxX0DfE4eHombGh4oJBBaItyMZYsj8X7xqTitBQ-zfDZEoEWS10HufjmdmcsrQ2lzPTOINiJoYp3nLz5Vv_MgaXaiKluxaDw-o2aMhE6myvU_Gx_UzavmGUcX3fazdqbAw1eg5SvBtCV_o9jePEJsQA

###