###
#Check if game service is working
GET https://localhost:4430/api/game/test/


################################################################
#                                                              #
#       Tests Users (endpoint called by the auth service       #
#                                                              #
################################################################

###add user to db

post https://localhost:4430/api/auth/signup/
Content-Type: application/json

{
  "username": "dd",
  "password": "Pass12456!",
  "email": "d@gmail.com"
}

###
#get user token
POST https://localhost:4430/api/auth/token/
Content-Type: application/json

{
  "username": "dd",
  "password": "Pass12456!"

}

###
#delete user
DELETE  https://localhost:4430/api/auth/delete/dd/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5NDczOTI1LCJpYXQiOjE3Mzk0Njg1MjUsImp0aSI6ImFmMmFjYTkyN2U5MjRiMzU4YWVlYmFjZWEwOWUxNThhIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJkZCJ9.TKODLnEGYcqvz0DB1qjp0opLhj3zoXTUwqbx5nHxYfrfyms4HqdpypUlYd-kiRwBb3l9lgGS3JEu--uM-yH1iGqWqt0bhCukMwV4mgn3c6xoMIYcECo4COBw41O3X8FkcAqpI799recCi6h-Z5XF20sihGh-h8ss2fBZtl5LOBHc5-3f5yZKISoZ2VAnBUdOSvg0J0NzEfz_p3-df_qcHf4TGJR5P3fnatlGsN-ERtAVW5vKHo3gqDIIqxtzcLEUgvH8MGaeynEbIckqF8JzqkPe_cU3g3Ch2rw10ZZi4UnuJRw-XDg114SyQF0Xs9OsHoDXkK_5w_K-Vrx4jqgxNw

################################################################
#                                                              #
#                          Game tests                          #
#                                                              #
################################################################


# ************************** CREATE ************************** #

###
#create game (for room service)
POST https://localhost:4430/api/game/create_game/id_hihi/
# Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4ODY0Mzk1LCJpYXQiOjE3Mzg4NTg5OTUsImp0aSI6ImE2OTdhMTk4M2I2OTQyZDc5Y2VmOTYwNTNhNDk1N2FkIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.a32f7IY-x3JvyUT3IDHDOevlSjML_sdaQcJztGrk4rKCgle5VmeFKEwol1uO__FeNE1hgMzF9CridmSdjJbUiJYHrNF4dsa3QEpisOt6BGM1bDu316v6RyUyfaTtA2k_o8VeG9GcAI6B2OkxswtmRePW5vENCLycVTPTM5CL76oekS8OVxrV8B7rcwytOYr0tXXFd-lbYFUtBWrNHmdRxCfs9iElPhqzg9OJg0A_nnKPXKwwwxb3uKAqT3VC5bgFZxgpMEa9Gj5ZwKfrNF7fEieQU3S3RN8VHXHKn2FrO6fsQa8AmXLSg3FR7IDsUpK0XOY7zclN76zjKx3wPsWOoA

###
#join game (for room service)
POST https://localhost:4430/api/game/join_game/id_hihi/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4ODgwNzgwLCJpYXQiOjE3Mzg4NzUzODAsImp0aSI6IjZkNDc1ZjgwOTQyNDQyZDdhNmUwODNmMTQzZWU1NjQzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0NF91c2VyIn0.MvPR_Tk0hi58wQNb0QCoiEe5mAnrPsYqa2qK5G-EXPeD0suZmzHTLb1iZmLRfgqubWZfnl45k_vPOT81celAXzF0OqkvmudxIEhN04GtlE9Mf4GP4Wn9QQLi7KxR9L6wrzaGoquWo3X8EBjSEcRYW3OVKSjuqKs2FcESl9XibFyqyjx6H_6NQElnl61eHbwF_KUko08UxbuAHXpphDklQErbAEA4IN4UZ0XhRa4E851HG-pT_TrFtRXIQFWjDPPA8QBfZFORFrQsIKuEU-zELmD61LaGvGy7gm32-1Y8-xrPJS4wJ6seAqOYWEHIEMxg9i6F5m-a9j_rfnA7e--AXQ

# *************************** READ *************************** #

###
#get a list of all games
GET https://localhost:4430/api/game/list_all_games/

###
#get the gamestate
GET https://localhost:4430/api/game/gamestate/id_hihi/

# **************************** PUT *************************** #

# ************************** DELETE ************************** #

###
#delete game
DELETE https://localhost:4430/api/game/delete_game/id_hihi/

