###
#check if tournament service is working
GET https://localhost:4430/api/tournament/test/

################################################################
#                                                              #
#                       Tournament tests                       #
#                                                              #
################################################################

# ************************** CREATE ************************** #

#create tournament
POST https://localhost:4430/api/tournament/create_tournament/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTk3MjI4LCJpYXQiOjE3Mzc5OTE4MjgsImp0aSI6ImVkNDgxY2NjM2Y3ODQwNTc4ZWU0NDdjYWQzMjlkMWY4IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.at6RtdCVaAd815b1D8fS55li4reP9jIO3EYE-PVvgmN7vrfVwbCVlBtwcFG3x7zgAzQPhe-Dkysm7fmeKjVS9GQhsHePDE6m4wL-v40vee1W77HQCFFBgssMYtIPoYTCumPboP9MtXQ4fNTVCpY5Ui0IPdphhjG7zDrix6nXr5PWsyCmtzx09Iq085VYl4ed7TCpEtn3Lv3St8RRHMclb1VfUvPpqk9K0jJRIiRCcvZaChrVkKNh01YVTCrsBvFom6mC8rZv-mS1ZQqDl__EAUCdhmxmWJMThP80hqde4-NKmuPrz09QmJdYncRV0dMOekXHr0g-OI0hsaCxiYBHQg
Content-Type: application/json

{
    "name": "hjjmm",
    "users": ["lol", "rinma"]
}

# *************************** READ *************************** #

###
#get tournament stats
GET https://localhost:4430/api/tournament/36d92f06-38f8-4b00-97fc-ca93324c0f3a/ranking/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTk3MjI4LCJpYXQiOjE3Mzc5OTE4MjgsImp0aSI6ImVkNDgxY2NjM2Y3ODQwNTc4ZWU0NDdjYWQzMjlkMWY4IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.at6RtdCVaAd815b1D8fS55li4reP9jIO3EYE-PVvgmN7vrfVwbCVlBtwcFG3x7zgAzQPhe-Dkysm7fmeKjVS9GQhsHePDE6m4wL-v40vee1W77HQCFFBgssMYtIPoYTCumPboP9MtXQ4fNTVCpY5Ui0IPdphhjG7zDrix6nXr5PWsyCmtzx09Iq085VYl4ed7TCpEtn3Lv3St8RRHMclb1VfUvPpqk9K0jJRIiRCcvZaChrVkKNh01YVTCrsBvFom6mC8rZv-mS1ZQqDl__EAUCdhmxmWJMThP80hqde4-NKmuPrz09QmJdYncRV0dMOekXHr0g-OI0hsaCxiYBHQg

###
#list all tournament
GET https://localhost:4430/api/tournament/list/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTk3MjI4LCJpYXQiOjE3Mzc5OTE4MjgsImp0aSI6ImVkNDgxY2NjM2Y3ODQwNTc4ZWU0NDdjYWQzMjlkMWY4IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.at6RtdCVaAd815b1D8fS55li4reP9jIO3EYE-PVvgmN7vrfVwbCVlBtwcFG3x7zgAzQPhe-Dkysm7fmeKjVS9GQhsHePDE6m4wL-v40vee1W77HQCFFBgssMYtIPoYTCumPboP9MtXQ4fNTVCpY5Ui0IPdphhjG7zDrix6nXr5PWsyCmtzx09Iq085VYl4ed7TCpEtn3Lv3St8RRHMclb1VfUvPpqk9K0jJRIiRCcvZaChrVkKNh01YVTCrsBvFom6mC8rZv-mS1ZQqDl__EAUCdhmxmWJMThP80hqde4-NKmuPrz09QmJdYncRV0dMOekXHr0g-OI0hsaCxiYBHQg

###
#list tournaments waiting to play
GET https://localhost:4430/api/tournament/list/waiting/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTk3MjI4LCJpYXQiOjE3Mzc5OTE4MjgsImp0aSI6ImVkNDgxY2NjM2Y3ODQwNTc4ZWU0NDdjYWQzMjlkMWY4IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.at6RtdCVaAd815b1D8fS55li4reP9jIO3EYE-PVvgmN7vrfVwbCVlBtwcFG3x7zgAzQPhe-Dkysm7fmeKjVS9GQhsHePDE6m4wL-v40vee1W77HQCFFBgssMYtIPoYTCumPboP9MtXQ4fNTVCpY5Ui0IPdphhjG7zDrix6nXr5PWsyCmtzx09Iq085VYl4ed7TCpEtn3Lv3St8RRHMclb1VfUvPpqk9K0jJRIiRCcvZaChrVkKNh01YVTCrsBvFom6mC8rZv-mS1ZQqDl__EAUCdhmxmWJMThP80hqde4-NKmuPrz09QmJdYncRV0dMOekXHr0g-OI0hsaCxiYBHQg

###
#list tournaments still playing
GET https://localhost:4430/api/tournament/list/playing/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTk3MjI4LCJpYXQiOjE3Mzc5OTE4MjgsImp0aSI6ImVkNDgxY2NjM2Y3ODQwNTc4ZWU0NDdjYWQzMjlkMWY4IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.at6RtdCVaAd815b1D8fS55li4reP9jIO3EYE-PVvgmN7vrfVwbCVlBtwcFG3x7zgAzQPhe-Dkysm7fmeKjVS9GQhsHePDE6m4wL-v40vee1W77HQCFFBgssMYtIPoYTCumPboP9MtXQ4fNTVCpY5Ui0IPdphhjG7zDrix6nXr5PWsyCmtzx09Iq085VYl4ed7TCpEtn3Lv3St8RRHMclb1VfUvPpqk9K0jJRIiRCcvZaChrVkKNh01YVTCrsBvFom6mC8rZv-mS1ZQqDl__EAUCdhmxmWJMThP80hqde4-NKmuPrz09QmJdYncRV0dMOekXHr0g-OI0hsaCxiYBHQg

###
#list finished tournaments
GET https://localhost:4430/api/tournament/list/finished/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTk3MjI4LCJpYXQiOjE3Mzc5OTE4MjgsImp0aSI6ImVkNDgxY2NjM2Y3ODQwNTc4ZWU0NDdjYWQzMjlkMWY4IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.at6RtdCVaAd815b1D8fS55li4reP9jIO3EYE-PVvgmN7vrfVwbCVlBtwcFG3x7zgAzQPhe-Dkysm7fmeKjVS9GQhsHePDE6m4wL-v40vee1W77HQCFFBgssMYtIPoYTCumPboP9MtXQ4fNTVCpY5Ui0IPdphhjG7zDrix6nXr5PWsyCmtzx09Iq085VYl4ed7TCpEtn3Lv3St8RRHMclb1VfUvPpqk9K0jJRIiRCcvZaChrVkKNh01YVTCrsBvFom6mC8rZv-mS1ZQqDl__EAUCdhmxmWJMThP80hqde4-NKmuPrz09QmJdYncRV0dMOekXHr0g-OI0hsaCxiYBHQg

###
#count all tournament
GET https://localhost:4430/api/tournament/count/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTk3MjI4LCJpYXQiOjE3Mzc5OTE4MjgsImp0aSI6ImVkNDgxY2NjM2Y3ODQwNTc4ZWU0NDdjYWQzMjlkMWY4IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.at6RtdCVaAd815b1D8fS55li4reP9jIO3EYE-PVvgmN7vrfVwbCVlBtwcFG3x7zgAzQPhe-Dkysm7fmeKjVS9GQhsHePDE6m4wL-v40vee1W77HQCFFBgssMYtIPoYTCumPboP9MtXQ4fNTVCpY5Ui0IPdphhjG7zDrix6nXr5PWsyCmtzx09Iq085VYl4ed7TCpEtn3Lv3St8RRHMclb1VfUvPpqk9K0jJRIiRCcvZaChrVkKNh01YVTCrsBvFom6mC8rZv-mS1ZQqDl__EAUCdhmxmWJMThP80hqde4-NKmuPrz09QmJdYncRV0dMOekXHr0g-OI0hsaCxiYBHQg

###
#count tournaments waiting
GET https://localhost:4430/api/tournament/count/waiting/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTk3MjI4LCJpYXQiOjE3Mzc5OTE4MjgsImp0aSI6ImVkNDgxY2NjM2Y3ODQwNTc4ZWU0NDdjYWQzMjlkMWY4IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.at6RtdCVaAd815b1D8fS55li4reP9jIO3EYE-PVvgmN7vrfVwbCVlBtwcFG3x7zgAzQPhe-Dkysm7fmeKjVS9GQhsHePDE6m4wL-v40vee1W77HQCFFBgssMYtIPoYTCumPboP9MtXQ4fNTVCpY5Ui0IPdphhjG7zDrix6nXr5PWsyCmtzx09Iq085VYl4ed7TCpEtn3Lv3St8RRHMclb1VfUvPpqk9K0jJRIiRCcvZaChrVkKNh01YVTCrsBvFom6mC8rZv-mS1ZQqDl__EAUCdhmxmWJMThP80hqde4-NKmuPrz09QmJdYncRV0dMOekXHr0g-OI0hsaCxiYBHQg

###
#count tournaments still playing
GET https://localhost:4430/api/tournament/count/playing/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTk3MjI4LCJpYXQiOjE3Mzc5OTE4MjgsImp0aSI6ImVkNDgxY2NjM2Y3ODQwNTc4ZWU0NDdjYWQzMjlkMWY4IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.at6RtdCVaAd815b1D8fS55li4reP9jIO3EYE-PVvgmN7vrfVwbCVlBtwcFG3x7zgAzQPhe-Dkysm7fmeKjVS9GQhsHePDE6m4wL-v40vee1W77HQCFFBgssMYtIPoYTCumPboP9MtXQ4fNTVCpY5Ui0IPdphhjG7zDrix6nXr5PWsyCmtzx09Iq085VYl4ed7TCpEtn3Lv3St8RRHMclb1VfUvPpqk9K0jJRIiRCcvZaChrVkKNh01YVTCrsBvFom6mC8rZv-mS1ZQqDl__EAUCdhmxmWJMThP80hqde4-NKmuPrz09QmJdYncRV0dMOekXHr0g-OI0hsaCxiYBHQg

###
#count finished tournaments
GET https://localhost:4430/api/tournament/count/finished/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTk3MjI4LCJpYXQiOjE3Mzc5OTE4MjgsImp0aSI6ImVkNDgxY2NjM2Y3ODQwNTc4ZWU0NDdjYWQzMjlkMWY4IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.at6RtdCVaAd815b1D8fS55li4reP9jIO3EYE-PVvgmN7vrfVwbCVlBtwcFG3x7zgAzQPhe-Dkysm7fmeKjVS9GQhsHePDE6m4wL-v40vee1W77HQCFFBgssMYtIPoYTCumPboP9MtXQ4fNTVCpY5Ui0IPdphhjG7zDrix6nXr5PWsyCmtzx09Iq085VYl4ed7TCpEtn3Lv3St8RRHMclb1VfUvPpqk9K0jJRIiRCcvZaChrVkKNh01YVTCrsBvFom6mC8rZv-mS1ZQqDl__EAUCdhmxmWJMThP80hqde4-NKmuPrz09QmJdYncRV0dMOekXHr0g-OI0hsaCxiYBHQg

# ************************** DELETE ************************** #

###
#delete tournament
DELETE https://localhost:4430/api/tournament/delete/213404ba-e5d2-418c-a2b3-1a6d45099cb3/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTk3MjI4LCJpYXQiOjE3Mzc5OTE4MjgsImp0aSI6ImVkNDgxY2NjM2Y3ODQwNTc4ZWU0NDdjYWQzMjlkMWY4IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.at6RtdCVaAd815b1D8fS55li4reP9jIO3EYE-PVvgmN7vrfVwbCVlBtwcFG3x7zgAzQPhe-Dkysm7fmeKjVS9GQhsHePDE6m4wL-v40vee1W77HQCFFBgssMYtIPoYTCumPboP9MtXQ4fNTVCpY5Ui0IPdphhjG7zDrix6nXr5PWsyCmtzx09Iq085VYl4ed7TCpEtn3Lv3St8RRHMclb1VfUvPpqk9K0jJRIiRCcvZaChrVkKNh01YVTCrsBvFom6mC8rZv-mS1ZQqDl__EAUCdhmxmWJMThP80hqde4-NKmuPrz09QmJdYncRV0dMOekXHr0g-OI0hsaCxiYBHQg

################################################################
#                                                              #
#                Tournament service User tests                 #
#                   (mauvais tests : a MAJ)                    #
#                                                              #
################################################################

# ************************** CREATE ************************** #

###
#create user
POST https://localhost:4430/api/tournament/create/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTk3MjI4LCJpYXQiOjE3Mzc5OTE4MjgsImp0aSI6ImVkNDgxY2NjM2Y3ODQwNTc4ZWU0NDdjYWQzMjlkMWY4IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.at6RtdCVaAd815b1D8fS55li4reP9jIO3EYE-PVvgmN7vrfVwbCVlBtwcFG3x7zgAzQPhe-Dkysm7fmeKjVS9GQhsHePDE6m4wL-v40vee1W77HQCFFBgssMYtIPoYTCumPboP9MtXQ4fNTVCpY5Ui0IPdphhjG7zDrix6nXr5PWsyCmtzx09Iq085VYl4ed7TCpEtn3Lv3St8RRHMclb1VfUvPpqk9K0jJRIiRCcvZaChrVkKNh01YVTCrsBvFom6mC8rZv-mS1ZQqDl__EAUCdhmxmWJMThP80hqde4-NKmuPrz09QmJdYncRV0dMOekXHr0g-OI0hsaCxiYBHQg

# *************************** READ *************************** #

###
#get a list of users
GET https://localhost:4430/api/tournament/list/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTk3MjI4LCJpYXQiOjE3Mzc5OTE4MjgsImp0aSI6ImVkNDgxY2NjM2Y3ODQwNTc4ZWU0NDdjYWQzMjlkMWY4IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.at6RtdCVaAd815b1D8fS55li4reP9jIO3EYE-PVvgmN7vrfVwbCVlBtwcFG3x7zgAzQPhe-Dkysm7fmeKjVS9GQhsHePDE6m4wL-v40vee1W77HQCFFBgssMYtIPoYTCumPboP9MtXQ4fNTVCpY5Ui0IPdphhjG7zDrix6nXr5PWsyCmtzx09Iq085VYl4ed7TCpEtn3Lv3St8RRHMclb1VfUvPpqk9K0jJRIiRCcvZaChrVkKNh01YVTCrsBvFom6mC8rZv-mS1ZQqDl__EAUCdhmxmWJMThP80hqde4-NKmuPrz09QmJdYncRV0dMOekXHr0g-OI0hsaCxiYBHQg

# **************************** PUT *************************** #

###
#update user
PUT https://localhost:4430/api/tournament/update/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTk3MjI4LCJpYXQiOjE3Mzc5OTE4MjgsImp0aSI6ImVkNDgxY2NjM2Y3ODQwNTc4ZWU0NDdjYWQzMjlkMWY4IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.at6RtdCVaAd815b1D8fS55li4reP9jIO3EYE-PVvgmN7vrfVwbCVlBtwcFG3x7zgAzQPhe-Dkysm7fmeKjVS9GQhsHePDE6m4wL-v40vee1W77HQCFFBgssMYtIPoYTCumPboP9MtXQ4fNTVCpY5Ui0IPdphhjG7zDrix6nXr5PWsyCmtzx09Iq085VYl4ed7TCpEtn3Lv3St8RRHMclb1VfUvPpqk9K0jJRIiRCcvZaChrVkKNh01YVTCrsBvFom6mC8rZv-mS1ZQqDl__EAUCdhmxmWJMThP80hqde4-NKmuPrz09QmJdYncRV0dMOekXHr0g-OI0hsaCxiYBHQg

# ************************** DELETE ************************** #

###
#delete user
DELETE  https://localhost:4430/api/tournament/delete/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTk3MjI4LCJpYXQiOjE3Mzc5OTE4MjgsImp0aSI6ImVkNDgxY2NjM2Y3ODQwNTc4ZWU0NDdjYWQzMjlkMWY4IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.at6RtdCVaAd815b1D8fS55li4reP9jIO3EYE-PVvgmN7vrfVwbCVlBtwcFG3x7zgAzQPhe-Dkysm7fmeKjVS9GQhsHePDE6m4wL-v40vee1W77HQCFFBgssMYtIPoYTCumPboP9MtXQ4fNTVCpY5Ui0IPdphhjG7zDrix6nXr5PWsyCmtzx09Iq085VYl4ed7TCpEtn3Lv3St8RRHMclb1VfUvPpqk9K0jJRIiRCcvZaChrVkKNh01YVTCrsBvFom6mC8rZv-mS1ZQqDl__EAUCdhmxmWJMThP80hqde4-NKmuPrz09QmJdYncRV0dMOekXHr0g-OI0hsaCxiYBHQg
