################################################################
#                                                              #
#                       Create user                            #
#                                                              #
################################################################

#create user1
post https://localhost:4430/api/auth/signup/
Content-Type: application/json

{
  "username": "bidon",
  "password": "Pass12456!",
  "email": "d@gmail.com"
}
###

#create user2
post https://localhost:4430/api/auth/signup/
Content-Type: application/json

{
  "username": "tkt",
  "password": "Pass12456!",
  "email": "oui@gmail.com"
}
###

#get user1 token
POST https://localhost:4430/api/auth/token/
Content-Type: application/json

{
  "username": "bidon",
  "password": "Pass12456!"
}
###

#get user2 token
POST https://localhost:4430/api/auth/token/
Content-Type: application/json

{
  "username": "tkt",
  "password": "Pass12456!"
}
###

#check if tournament service is working
GET https://localhost:4430/api/tournament/test/
###
################################################################
#                                                              #
#                       Tournament tests                       #
#                                                              #
################################################################

# ************************** POST ************************** #

#create tournament
POST https://localhost:4430/api/tournament/create_tournament/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMzIzNjgzLCJpYXQiOjE3NDAzMTgyODMsImp0aSI6ImNjMmU3ZTgxYmVlMzRjYzQ4OTU5NjA0OTExNWI2MGVlIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJiaWRvbiJ9.C5Gyo91oLrgq3WyW6QWjyUoreMzlMBkZ-h8vNFgFCNnhLmP4Wvizd5uzWCWHyAz8k621d0tRKDHQ0a_2bDZtVpmL6Bm_dORdu_eiG6A5_9lC6yv6TgiMtSiGxise7M9rIZ6dnlXcIgO_n2q62Ml7R0VwSlE5SYyFpdMrsUuMrX9wfzexwfvTk5kGcwrezNCV7OrYAf-WVk-JhNZbZHo2UoeukyyAI-n4jmUrbm2oD8jaEunwcPilYpVNUIJeRHvlIxY79njVTKbuG59Ao-s4B7xi-kmHe7SDd2JE1Fx7NnO0XVjekGSX7EusF2GVVbaym3lze_sB9ju19eOB0khGKw
Content-Type: application/json

{
    "name": "chokbar de bz",
    "status": "playing",
    "users_count": 32,
    "owner": 1,
    "max_users": 16
}
###

#join tournament
POST https://localhost:4430/api/tournament/join/6893cb56-b650-4d20-a2c1-bb1dc6a1dd16/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMzIzNzEwLCJpYXQiOjE3NDAzMTgzMTAsImp0aSI6ImFhNTYzNDQwZjEzMDQ2NDBiMDdjYTg2Yzc4Y2RjOTc1IiwidXNlcl9pZCI6MiwidXNlcm5hbWUiOiJ0a3QifQ.DThJP5OsbAjtn-fQwD5smjvzAR6ZdwvJS2BonCC9lfisplhzlKLwDEZfT1pVMhyGBkHcnMhhimxtYk1sr6E6bjrZ3G24LGfKpZNiX7I4ArZCnTYQKGmsvZ5POvRMYTMnG_a3CPLOBb4GdBQjM8k_DLG0EmDxH7Mkk95V8r6XPLL1jlLgV8plS4Dz2cm70NBEczEhaplEHezGZHMz3txhra8DGaUL-xF_7o1tCou5TFFcYBFT9PZ1teZ1S55MEUBCfEhhTkvlH8RkZca_l_5oAKdu9muC8yXps2QHBQ2QpzNh6YymvhVmOOi6e2SL3KkItkGayN49KwRYfNL128Y4tw
Content-Type: application/json

###

#launch tournament
POST https://localhost:4430/api/tournament/launch/6893cb56-b650-4d20-a2c1-bb1dc6a1dd16/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMzIzNjgzLCJpYXQiOjE3NDAzMTgyODMsImp0aSI6ImNjMmU3ZTgxYmVlMzRjYzQ4OTU5NjA0OTExNWI2MGVlIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJiaWRvbiJ9.C5Gyo91oLrgq3WyW6QWjyUoreMzlMBkZ-h8vNFgFCNnhLmP4Wvizd5uzWCWHyAz8k621d0tRKDHQ0a_2bDZtVpmL6Bm_dORdu_eiG6A5_9lC6yv6TgiMtSiGxise7M9rIZ6dnlXcIgO_n2q62Ml7R0VwSlE5SYyFpdMrsUuMrX9wfzexwfvTk5kGcwrezNCV7OrYAf-WVk-JhNZbZHo2UoeukyyAI-n4jmUrbm2oD8jaEunwcPilYpVNUIJeRHvlIxY79njVTKbuG59Ao-s4B7xi-kmHe7SDd2JE1Fx7NnO0XVjekGSX7EusF2GVVbaym3lze_sB9ju19eOB0khGKw
Content-Type: application/json

###

# *************************** DELETE *************************** #

#delete tournament
DELETE https://localhost:4430/api/tournament/delete_tournament/2c89054c-32db-4f06-9ad3-0edffb203df2/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMzIzNjgzLCJpYXQiOjE3NDAzMTgyODMsImp0aSI6ImNjMmU3ZTgxYmVlMzRjYzQ4OTU5NjA0OTExNWI2MGVlIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJiaWRvbiJ9.C5Gyo91oLrgq3WyW6QWjyUoreMzlMBkZ-h8vNFgFCNnhLmP4Wvizd5uzWCWHyAz8k621d0tRKDHQ0a_2bDZtVpmL6Bm_dORdu_eiG6A5_9lC6yv6TgiMtSiGxise7M9rIZ6dnlXcIgO_n2q62Ml7R0VwSlE5SYyFpdMrsUuMrX9wfzexwfvTk5kGcwrezNCV7OrYAf-WVk-JhNZbZHo2UoeukyyAI-n4jmUrbm2oD8jaEunwcPilYpVNUIJeRHvlIxY79njVTKbuG59Ao-s4B7xi-kmHe7SDd2JE1Fx7NnO0XVjekGSX7EusF2GVVbaym3lze_sB9ju19eOB0khGKw
###

# *************************** READ *************************** #

#get tournament stats
GET https://localhost:4430/api/tournament/36d92f06-38f8-4b00-97fc-ca93324c0f3a/ranking/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTk3MjI4LCJpYXQiOjE3Mzc5OTE4MjgsImp0aSI6ImVkNDgxY2NjM2Y3ODQwNTc4ZWU0NDdjYWQzMjlkMWY4IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.at6RtdCVaAd815b1D8fS55li4reP9jIO3EYE-PVvgmN7vrfVwbCVlBtwcFG3x7zgAzQPhe-Dkysm7fmeKjVS9GQhsHePDE6m4wL-v40vee1W77HQCFFBgssMYtIPoYTCumPboP9MtXQ4fNTVCpY5Ui0IPdphhjG7zDrix6nXr5PWsyCmtzx09Iq085VYl4ed7TCpEtn3Lv3St8RRHMclb1VfUvPpqk9K0jJRIiRCcvZaChrVkKNh01YVTCrsBvFom6mC8rZv-mS1ZQqDl__EAUCdhmxmWJMThP80hqde4-NKmuPrz09QmJdYncRV0dMOekXHr0g-OI0hsaCxiYBHQg

###
#list all tournament
GET https://localhost:4430/api/tournament/list/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMzIzNjgzLCJpYXQiOjE3NDAzMTgyODMsImp0aSI6ImNjMmU3ZTgxYmVlMzRjYzQ4OTU5NjA0OTExNWI2MGVlIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJiaWRvbiJ9.C5Gyo91oLrgq3WyW6QWjyUoreMzlMBkZ-h8vNFgFCNnhLmP4Wvizd5uzWCWHyAz8k621d0tRKDHQ0a_2bDZtVpmL6Bm_dORdu_eiG6A5_9lC6yv6TgiMtSiGxise7M9rIZ6dnlXcIgO_n2q62Ml7R0VwSlE5SYyFpdMrsUuMrX9wfzexwfvTk5kGcwrezNCV7OrYAf-WVk-JhNZbZHo2UoeukyyAI-n4jmUrbm2oD8jaEunwcPilYpVNUIJeRHvlIxY79njVTKbuG59Ao-s4B7xi-kmHe7SDd2JE1Fx7NnO0XVjekGSX7EusF2GVVbaym3lze_sB9ju19eOB0khGKw

###
#list tournaments waiting to play
GET https://localhost:4430/api/tournament/list/waiting/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTk3MjI4LCJpYXQiOjE3Mzc5OTE4MjgsImp0aSI6ImVkNDgxY2NjM2Y3ODQwNTc4ZWU0NDdjYWQzMjlkMWY4IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.at6RtdCVaAd815b1D8fS55li4reP9jIO3EYE-PVvgmN7vrfVwbCVlBtwcFG3x7zgAzQPhe-Dkysm7fmeKjVS9GQhsHePDE6m4wL-v40vee1W77HQCFFBgssMYtIPoYTCumPboP9MtXQ4fNTVCpY5Ui0IPdphhjG7zDrix6nXr5PWsyCmtzx09Iq085VYl4ed7TCpEtn3Lv3St8RRHMclb1VfUvPpqk9K0jJRIiRCcvZaChrVkKNh01YVTCrsBvFom6mC8rZv-mS1ZQqDl__EAUCdhmxmWJMThP80hqde4-NKmuPrz09QmJdYncRV0dMOekXHr0g-OI0hsaCxiYBHQg

###
#list tournaments still playing
GET https://localhost:4430/api/tournament/list/playing/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTk3MjI4LCJpYXQiOjE3Mzc5OTE4MjgsImp0aSI6ImVkNDgxY2NjM2Y3ODQwNTc4ZWU0NDdjYWQzMjlkMWY4IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.at6RtdCVaAd815b1D8fS55li4reP9jIO3EYE-PVvgmN7vrfVwbCVlBtwcFG3x7zgAzQPhe-Dkysm7fmeKjVS9GQhsHePDE6m4wL-v40vee1W77HQCFFBgssMYtIPoYTCumPboP9MtXQ4fNTVCpY5Ui0IPdphhjG7zDrix6nXr5PWsyCmtzx09Iq085VYl4ed7TCpEtn3Lv3St8RRHMclb1VfUvPpqk9K0jJRIiRCcvZaChrVkKNh01YVTCrsBvFom6mC8rZv-mS1ZQqDl__EAUCdhmxmWJMThP80hqde4-NKmuPrz09QmJdYncRV0dMOekXHr0g-OI0hsaCxiYBHQg

###
#list finished tournaments
GET https://localhost:4430/api/tournament/list/finished/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTk3MjI4LCJpYXQiOjE3Mzc5OTE4MjgsImp0aSI6ImVkNDgxY2NjM2Y3ODQwNTc4ZWU0NDdjYWQzMjlkMWY4IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.at6RtdCVaAd815b1D8fS55li4reP9jIO3EYE-PVvgmN7vrfVwbCVlBtwcFG3x7zgAzQPhe-Dkysm7fmeKjVS9GQhsHePDE6m4wL-v40vee1W77HQCFFBgssMYtIPoYTCumPboP9MtXQ4fNTVCpY5Ui0IPdphhjG7zDrix6nXr5PWsyCmtzx09Iq085VYl4ed7TCpEtn3Lv3St8RRHMclb1VfUvPpqk9K0jJRIiRCcvZaChrVkKNh01YVTCrsBvFom6mC8rZv-mS1ZQqDl__EAUCdhmxmWJMThP80hqde4-NKmuPrz09QmJdYncRV0dMOekXHr0g-OI0hsaCxiYBHQg

###
#count all tournament
GET https://localhost:4430/api/tournament/count/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMDc4MTY0LCJpYXQiOjE3NDAwNzI3NjQsImp0aSI6IjY4NGU0YjliZmVlMjRkODliN2UwMDk3OWYwYThlYzBiIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJkZCJ9.SpU1ZsmWBwNMCjlliztY64Kgg1h8SBBLa0NzgajmjbEKMDoonRELHjWSmHazrFtllcXVNchNqCObblM-f4Aohyqs5xg6qAdOBBckLbrbLAKDQoIQGpmmFT-SuDeIlIun2fHxBiFt0rcXNAip5CpT5RqkKkt3P0UT-BmOR_X0k_PnMaNql0-6M1HCjPWvDb5HTqTT0A9AzzY8hldoNoFLqfbV8cxMUoFeg6D98NbCovN1Cj2PUBNAP1Xl5lgs9ntGTzEig3tFgb_spTXrTSZ-MIEZvorr_ZHlnAY5bQb1o_EWlI5Ju8jSDhEG4mnDg56EmXEk62amBdo8QQYgAy2XvQ

###
#count tournaments waiting
GET https://localhost:4430/api/tournament/count/waiting/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTk3MjI4LCJpYXQiOjE3Mzc5OTE4MjgsImp0aSI6ImVkNDgxY2NjM2Y3ODQwNTc4ZWU0NDdjYWQzMjlkMWY4IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.at6RtdCVaAd815b1D8fS55li4reP9jIO3EYE-PVvgmN7vrfVwbCVlBtwcFG3x7zgAzQPhe-Dkysm7fmeKjVS9GQhsHePDE6m4wL-v40vee1W77HQCFFBgssMYtIPoYTCumPboP9MtXQ4fNTVCpY5Ui0IPdphhjG7zDrix6nXr5PWsyCmtzx09Iq085VYl4ed7TCpEtn3Lv3St8RRHMclb1VfUvPpqk9K0jJRIiRCcvZaChrVkKNh01YVTCrsBvFom6mC8rZv-mS1ZQqDl__EAUCdhmxmWJMThP80hqde4-NKmuPrz09QmJdYncRV0dMOekXHr0g-OI0hsaCxiYBHQg

###
#count tournaments still playing
GET https://localhost:4430/api/tournament/count/playing/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTk3MjI4LCJpYXQiOjE3Mzc5OTE4MjgsImp0aSI6ImVkNDgxY2NjM2Y3ODQwNTc4ZWU0NDdjYWQzMjlkMWY4IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.at6RtdCVaAd815b1D8fS55li4reP9jIO3EYE-PVvgmN7vrfVwbCVlBtwcFG3x7zgAzQPhe-Dkysm7fmeKjVS9GQhsHePDE6m4wL-v40vee1W77HQCFFBgssMYtIPoYTCumPboP9MtXQ4fNTVCpY5Ui0IPdphhjG7zDrix6nXr5PWsyCmtzx09Iq085VYl4ed7TCpEtn3Lv3St8RRHMclb1VfUvPpqk9K0jJRIiRCcvZaChrVkKNh01YVTCrsBvFom6mC8rZv-mS1ZQqDl__EAUCdhmxmWJMThP80hqde4-NKmuPrz09QmJdYncRV0dMOekXHr0g-OI0hsaCxiYBHQg

###
#count finished tournaments
GET https://localhost:4430/api/tournament/count/finished/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTk3MjI4LCJpYXQiOjE3Mzc5OTE4MjgsImp0aSI6ImVkNDgxY2NjM2Y3ODQwNTc4ZWU0NDdjYWQzMjlkMWY4IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.at6RtdCVaAd815b1D8fS55li4reP9jIO3EYE-PVvgmN7vrfVwbCVlBtwcFG3x7zgAzQPhe-Dkysm7fmeKjVS9GQhsHePDE6m4wL-v40vee1W77HQCFFBgssMYtIPoYTCumPboP9MtXQ4fNTVCpY5Ui0IPdphhjG7zDrix6nXr5PWsyCmtzx09Iq085VYl4ed7TCpEtn3Lv3St8RRHMclb1VfUvPpqk9K0jJRIiRCcvZaChrVkKNh01YVTCrsBvFom6mC8rZv-mS1ZQqDl__EAUCdhmxmWJMThP80hqde4-NKmuPrz09QmJdYncRV0dMOekXHr0g-OI0hsaCxiYBHQg

################################################################
#                                                              #
#                Tournament service User tests                 #
#                   (mauvais tests : a MAJ)                    #
#                                                              #
################################################################

# ************************** CREATE ************************** #

###
#create user
POST https://localhost:4430/api/tournament/create/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMjQzMDk2LCJpYXQiOjE3NDAyMzc2OTYsImp0aSI6IjJkMmY1Y2Y0Y2ZmMTRiYTk5NjE4ZTgwOWYzMzY5Y2YyIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJiaWRvbiJ9.s8P_OEw1LhYDjkyu1bl0UCWgUoImTgReze3HkSeJMFwQi8U7ASWKHveCyMwM34YtnZS7hNL_A7E1emh8VxDBq5Nny2FSbVRdQqNIYo0Ga1M4PXjOXCszQxicESyN7kO5dgka1Bj1ldKb7tqejd0TbiwaJZtEnSml5lp_B3MIeONyTNWRiYsNTR0ysIP44TDuQv_jRCnnqKJTRufnpfesKt10mFpWRnmCiP-UhYGyaprIGbqjYDh8TjIB0lQw3q4PZ2vu9eY8RlirSOi7jQw2HHPHg5iBjbH5O0snovm7cJFskddtyuqm8oEJS4g9FYXoA4D3u-Wyzlux-UwPIBlFnQ

# *************************** READ *************************** #

###
#get a list of users
GET https://localhost:4430/api/tournament/list/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTk3MjI4LCJpYXQiOjE3Mzc5OTE4MjgsImp0aSI6ImVkNDgxY2NjM2Y3ODQwNTc4ZWU0NDdjYWQzMjlkMWY4IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.at6RtdCVaAd815b1D8fS55li4reP9jIO3EYE-PVvgmN7vrfVwbCVlBtwcFG3x7zgAzQPhe-Dkysm7fmeKjVS9GQhsHePDE6m4wL-v40vee1W77HQCFFBgssMYtIPoYTCumPboP9MtXQ4fNTVCpY5Ui0IPdphhjG7zDrix6nXr5PWsyCmtzx09Iq085VYl4ed7TCpEtn3Lv3St8RRHMclb1VfUvPpqk9K0jJRIiRCcvZaChrVkKNh01YVTCrsBvFom6mC8rZv-mS1ZQqDl__EAUCdhmxmWJMThP80hqde4-NKmuPrz09QmJdYncRV0dMOekXHr0g-OI0hsaCxiYBHQg

# **************************** PUT *************************** #

###
#update user
PUT https://localhost:4430/api/tournament/update/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTk3MjI4LCJpYXQiOjE3Mzc5OTE4MjgsImp0aSI6ImVkNDgxY2NjM2Y3ODQwNTc4ZWU0NDdjYWQzMjlkMWY4IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.at6RtdCVaAd815b1D8fS55li4reP9jIO3EYE-PVvgmN7vrfVwbCVlBtwcFG3x7zgAzQPhe-Dkysm7fmeKjVS9GQhsHePDE6m4wL-v40vee1W77HQCFFBgssMYtIPoYTCumPboP9MtXQ4fNTVCpY5Ui0IPdphhjG7zDrix6nXr5PWsyCmtzx09Iq085VYl4ed7TCpEtn3Lv3St8RRHMclb1VfUvPpqk9K0jJRIiRCcvZaChrVkKNh01YVTCrsBvFom6mC8rZv-mS1ZQqDl__EAUCdhmxmWJMThP80hqde4-NKmuPrz09QmJdYncRV0dMOekXHr0g-OI0hsaCxiYBHQg

# ************************** DELETE ************************** #

###
#delete user
DELETE  https://localhost:4430/api/tournament/delete/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTk3MjI4LCJpYXQiOjE3Mzc5OTE4MjgsImp0aSI6ImVkNDgxY2NjM2Y3ODQwNTc4ZWU0NDdjYWQzMjlkMWY4IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.at6RtdCVaAd815b1D8fS55li4reP9jIO3EYE-PVvgmN7vrfVwbCVlBtwcFG3x7zgAzQPhe-Dkysm7fmeKjVS9GQhsHePDE6m4wL-v40vee1W77HQCFFBgssMYtIPoYTCumPboP9MtXQ4fNTVCpY5Ui0IPdphhjG7zDrix6nXr5PWsyCmtzx09Iq085VYl4ed7TCpEtn3Lv3St8RRHMclb1VfUvPpqk9K0jJRIiRCcvZaChrVkKNh01YVTCrsBvFom6mC8rZv-mS1ZQqDl__EAUCdhmxmWJMThP80hqde4-NKmuPrz09QmJdYncRV0dMOekXHr0g-OI0hsaCxiYBHQg
