###
#check if room service is working
GET https://localhost:4430/api/rooms/test/

################################################################
#                                                              #
#                          Room tests                          #
#                                                              #
################################################################

# ************************** CREATE ************************** #

### attention : un user peut creer plein de room: voir si on change ou non
#create room
POST https://localhost:4430/api/rooms/create_room/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3MDQ2NzI0LCJpYXQiOjE3MzcwNDEzMjQsImp0aSI6ImExNGM1OTdjNWJjOTQ4YzRhOTRjMTJiZGIyYjhiNmIzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.rCT4_JCY-W1ACjrOGC-LVU2IYCMVRgaAZgBfY8mIFyBAU3r1vOlKmshtpwM5yrr4ain7cWj04lyYVQGY5p--sYAuIjx6SfSpb2ZU3hm3LqUsLcxaGfKYhx-iiWku4qxVFRzDn-M04Jf2FCpTmDRO9UFC_FWYoTPdbPW6ZDJoLve6vseUDIPIZ8WEZhkx0dvurB-BgN99DV-kkE_V9qLi-HdaIGwaq9klaN1B9jNY1XRYPpBLIQ_MFKSmH77om1x6hBjfXhXi4_3FawCpuOa2sGkfax-RGfVs4F1p1BFAZzBfXheHd2DczQtctkr_JstonzCjv-nSbCjQNU0kU3lvRA

###
#join room
POST https://localhost:4430/api/rooms/join_room/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3MDQ2NzI0LCJpYXQiOjE3MzcwNDEzMjQsImp0aSI6ImExNGM1OTdjNWJjOTQ4YzRhOTRjMTJiZGIyYjhiNmIzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.rCT4_JCY-W1ACjrOGC-LVU2IYCMVRgaAZgBfY8mIFyBAU3r1vOlKmshtpwM5yrr4ain7cWj04lyYVQGY5p--sYAuIjx6SfSpb2ZU3hm3LqUsLcxaGfKYhx-iiWku4qxVFRzDn-M04Jf2FCpTmDRO9UFC_FWYoTPdbPW6ZDJoLve6vseUDIPIZ8WEZhkx0dvurB-BgN99DV-kkE_V9qLi-HdaIGwaq9klaN1B9jNY1XRYPpBLIQ_MFKSmH77om1x6hBjfXhXi4_3FawCpuOa2sGkfax-RGfVs4F1p1BFAZzBfXheHd2DczQtctkr_JstonzCjv-nSbCjQNU0kU3lvRA

# *************************** READ *************************** #

###
#list all rooms
GET https://localhost:4430/api/rooms/list_all_rooms/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3MDQ2NzI0LCJpYXQiOjE3MzcwNDEzMjQsImp0aSI6ImExNGM1OTdjNWJjOTQ4YzRhOTRjMTJiZGIyYjhiNmIzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.rCT4_JCY-W1ACjrOGC-LVU2IYCMVRgaAZgBfY8mIFyBAU3r1vOlKmshtpwM5yrr4ain7cWj04lyYVQGY5p--sYAuIjx6SfSpb2ZU3hm3LqUsLcxaGfKYhx-iiWku4qxVFRzDn-M04Jf2FCpTmDRO9UFC_FWYoTPdbPW6ZDJoLve6vseUDIPIZ8WEZhkx0dvurB-BgN99DV-kkE_V9qLi-HdaIGwaq9klaN1B9jNY1XRYPpBLIQ_MFKSmH77om1x6hBjfXhXi4_3FawCpuOa2sGkfax-RGfVs4F1p1BFAZzBfXheHd2DczQtctkr_JstonzCjv-nSbCjQNU0kU3lvRA

###
#list available rooms
GET https://localhost:4430/api/rooms/list_available_rooms/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3MDQ2NzI0LCJpYXQiOjE3MzcwNDEzMjQsImp0aSI6ImExNGM1OTdjNWJjOTQ4YzRhOTRjMTJiZGIyYjhiNmIzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.rCT4_JCY-W1ACjrOGC-LVU2IYCMVRgaAZgBfY8mIFyBAU3r1vOlKmshtpwM5yrr4ain7cWj04lyYVQGY5p--sYAuIjx6SfSpb2ZU3hm3LqUsLcxaGfKYhx-iiWku4qxVFRzDn-M04Jf2FCpTmDRO9UFC_FWYoTPdbPW6ZDJoLve6vseUDIPIZ8WEZhkx0dvurB-BgN99DV-kkE_V9qLi-HdaIGwaq9klaN1B9jNY1XRYPpBLIQ_MFKSmH77om1x6hBjfXhXi4_3FawCpuOa2sGkfax-RGfVs4F1p1BFAZzBfXheHd2DczQtctkr_JstonzCjv-nSbCjQNU0kU3lvRA

###
#list locked rooms
GET https://localhost:4430/api/rooms/list_locked_rooms/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3MDQ2NzI0LCJpYXQiOjE3MzcwNDEzMjQsImp0aSI6ImExNGM1OTdjNWJjOTQ4YzRhOTRjMTJiZGIyYjhiNmIzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.rCT4_JCY-W1ACjrOGC-LVU2IYCMVRgaAZgBfY8mIFyBAU3r1vOlKmshtpwM5yrr4ain7cWj04lyYVQGY5p--sYAuIjx6SfSpb2ZU3hm3LqUsLcxaGfKYhx-iiWku4qxVFRzDn-M04Jf2FCpTmDRO9UFC_FWYoTPdbPW6ZDJoLve6vseUDIPIZ8WEZhkx0dvurB-BgN99DV-kkE_V9qLi-HdaIGwaq9klaN1B9jNY1XRYPpBLIQ_MFKSmH77om1x6hBjfXhXi4_3FawCpuOa2sGkfax-RGfVs4F1p1BFAZzBfXheHd2DczQtctkr_JstonzCjv-nSbCjQNU0kU3lvRA

###
#count all rooms
GET https://localhost:4430/api/rooms/count_all_rooms/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3MDQ2NzI0LCJpYXQiOjE3MzcwNDEzMjQsImp0aSI6ImExNGM1OTdjNWJjOTQ4YzRhOTRjMTJiZGIyYjhiNmIzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.rCT4_JCY-W1ACjrOGC-LVU2IYCMVRgaAZgBfY8mIFyBAU3r1vOlKmshtpwM5yrr4ain7cWj04lyYVQGY5p--sYAuIjx6SfSpb2ZU3hm3LqUsLcxaGfKYhx-iiWku4qxVFRzDn-M04Jf2FCpTmDRO9UFC_FWYoTPdbPW6ZDJoLve6vseUDIPIZ8WEZhkx0dvurB-BgN99DV-kkE_V9qLi-HdaIGwaq9klaN1B9jNY1XRYPpBLIQ_MFKSmH77om1x6hBjfXhXi4_3FawCpuOa2sGkfax-RGfVs4F1p1BFAZzBfXheHd2DczQtctkr_JstonzCjv-nSbCjQNU0kU3lvRA

###
#count available rooms
GET https://localhost:4430/api/rooms/count_available_rooms/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3MDQ2NzI0LCJpYXQiOjE3MzcwNDEzMjQsImp0aSI6ImExNGM1OTdjNWJjOTQ4YzRhOTRjMTJiZGIyYjhiNmIzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.rCT4_JCY-W1ACjrOGC-LVU2IYCMVRgaAZgBfY8mIFyBAU3r1vOlKmshtpwM5yrr4ain7cWj04lyYVQGY5p--sYAuIjx6SfSpb2ZU3hm3LqUsLcxaGfKYhx-iiWku4qxVFRzDn-M04Jf2FCpTmDRO9UFC_FWYoTPdbPW6ZDJoLve6vseUDIPIZ8WEZhkx0dvurB-BgN99DV-kkE_V9qLi-HdaIGwaq9klaN1B9jNY1XRYPpBLIQ_MFKSmH77om1x6hBjfXhXi4_3FawCpuOa2sGkfax-RGfVs4F1p1BFAZzBfXheHd2DczQtctkr_JstonzCjv-nSbCjQNU0kU3lvRA

###
#count locked rooms
GET https://localhost:4430/api/rooms/count_locked_rooms/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3MDQ2NzI0LCJpYXQiOjE3MzcwNDEzMjQsImp0aSI6ImExNGM1OTdjNWJjOTQ4YzRhOTRjMTJiZGIyYjhiNmIzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.rCT4_JCY-W1ACjrOGC-LVU2IYCMVRgaAZgBfY8mIFyBAU3r1vOlKmshtpwM5yrr4ain7cWj04lyYVQGY5p--sYAuIjx6SfSpb2ZU3hm3LqUsLcxaGfKYhx-iiWku4qxVFRzDn-M04Jf2FCpTmDRO9UFC_FWYoTPdbPW6ZDJoLve6vseUDIPIZ8WEZhkx0dvurB-BgN99DV-kkE_V9qLi-HdaIGwaq9klaN1B9jNY1XRYPpBLIQ_MFKSmH77om1x6hBjfXhXi4_3FawCpuOa2sGkfax-RGfVs4F1p1BFAZzBfXheHd2DczQtctkr_JstonzCjv-nSbCjQNU0kU3lvRA

# ************************** DELETE ************************** #

###
#delete rooms
DELETE https://localhost:4430/api/rooms/delete_room/room_e3aaed1d/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3MDQ2NzI0LCJpYXQiOjE3MzcwNDEzMjQsImp0aSI6ImExNGM1OTdjNWJjOTQ4YzRhOTRjMTJiZGIyYjhiNmIzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.rCT4_JCY-W1ACjrOGC-LVU2IYCMVRgaAZgBfY8mIFyBAU3r1vOlKmshtpwM5yrr4ain7cWj04lyYVQGY5p--sYAuIjx6SfSpb2ZU3hm3LqUsLcxaGfKYhx-iiWku4qxVFRzDn-M04Jf2FCpTmDRO9UFC_FWYoTPdbPW6ZDJoLve6vseUDIPIZ8WEZhkx0dvurB-BgN99DV-kkE_V9qLi-HdaIGwaq9klaN1B9jNY1XRYPpBLIQ_MFKSmH77om1x6hBjfXhXi4_3FawCpuOa2sGkfax-RGfVs4F1p1BFAZzBfXheHd2DczQtctkr_JstonzCjv-nSbCjQNU0kU3lvRA

################################################################
#                                                              #
#                   Room service User tests                    #
#                   (mauvais tests : a MAJ)                    #
#                                                              #
################################################################

# ************************** CREATE ************************** #

###
#create user
POST https://localhost:4430/api/rooms/create/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3MDQ2NzI0LCJpYXQiOjE3MzcwNDEzMjQsImp0aSI6ImExNGM1OTdjNWJjOTQ4YzRhOTRjMTJiZGIyYjhiNmIzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.rCT4_JCY-W1ACjrOGC-LVU2IYCMVRgaAZgBfY8mIFyBAU3r1vOlKmshtpwM5yrr4ain7cWj04lyYVQGY5p--sYAuIjx6SfSpb2ZU3hm3LqUsLcxaGfKYhx-iiWku4qxVFRzDn-M04Jf2FCpTmDRO9UFC_FWYoTPdbPW6ZDJoLve6vseUDIPIZ8WEZhkx0dvurB-BgN99DV-kkE_V9qLi-HdaIGwaq9klaN1B9jNY1XRYPpBLIQ_MFKSmH77om1x6hBjfXhXi4_3FawCpuOa2sGkfax-RGfVs4F1p1BFAZzBfXheHd2DczQtctkr_JstonzCjv-nSbCjQNU0kU3lvRA

# *************************** READ *************************** #

###
#get a list of users
GET https://localhost:4430/api/rooms/list/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3MDQ2NzI0LCJpYXQiOjE3MzcwNDEzMjQsImp0aSI6ImExNGM1OTdjNWJjOTQ4YzRhOTRjMTJiZGIyYjhiNmIzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.rCT4_JCY-W1ACjrOGC-LVU2IYCMVRgaAZgBfY8mIFyBAU3r1vOlKmshtpwM5yrr4ain7cWj04lyYVQGY5p--sYAuIjx6SfSpb2ZU3hm3LqUsLcxaGfKYhx-iiWku4qxVFRzDn-M04Jf2FCpTmDRO9UFC_FWYoTPdbPW6ZDJoLve6vseUDIPIZ8WEZhkx0dvurB-BgN99DV-kkE_V9qLi-HdaIGwaq9klaN1B9jNY1XRYPpBLIQ_MFKSmH77om1x6hBjfXhXi4_3FawCpuOa2sGkfax-RGfVs4F1p1BFAZzBfXheHd2DczQtctkr_JstonzCjv-nSbCjQNU0kU3lvRA

# **************************** PUT *************************** #

###
#update user
PUT https://localhost:4430/api/rooms/update/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3MDQ2NzI0LCJpYXQiOjE3MzcwNDEzMjQsImp0aSI6ImExNGM1OTdjNWJjOTQ4YzRhOTRjMTJiZGIyYjhiNmIzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.rCT4_JCY-W1ACjrOGC-LVU2IYCMVRgaAZgBfY8mIFyBAU3r1vOlKmshtpwM5yrr4ain7cWj04lyYVQGY5p--sYAuIjx6SfSpb2ZU3hm3LqUsLcxaGfKYhx-iiWku4qxVFRzDn-M04Jf2FCpTmDRO9UFC_FWYoTPdbPW6ZDJoLve6vseUDIPIZ8WEZhkx0dvurB-BgN99DV-kkE_V9qLi-HdaIGwaq9klaN1B9jNY1XRYPpBLIQ_MFKSmH77om1x6hBjfXhXi4_3FawCpuOa2sGkfax-RGfVs4F1p1BFAZzBfXheHd2DczQtctkr_JstonzCjv-nSbCjQNU0kU3lvRA

# ************************** DELETE ************************** #

###
#delete user
DELETE  https://localhost:4430/api/rooms/delete/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3MDQ2NzI0LCJpYXQiOjE3MzcwNDEzMjQsImp0aSI6ImExNGM1OTdjNWJjOTQ4YzRhOTRjMTJiZGIyYjhiNmIzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.rCT4_JCY-W1ACjrOGC-LVU2IYCMVRgaAZgBfY8mIFyBAU3r1vOlKmshtpwM5yrr4ain7cWj04lyYVQGY5p--sYAuIjx6SfSpb2ZU3hm3LqUsLcxaGfKYhx-iiWku4qxVFRzDn-M04Jf2FCpTmDRO9UFC_FWYoTPdbPW6ZDJoLve6vseUDIPIZ8WEZhkx0dvurB-BgN99DV-kkE_V9qLi-HdaIGwaq9klaN1B9jNY1XRYPpBLIQ_MFKSmH77om1x6hBjfXhXi4_3FawCpuOa2sGkfax-RGfVs4F1p1BFAZzBfXheHd2DczQtctkr_JstonzCjv-nSbCjQNU0kU3lvRA
