###
#check if room service is working
GET https://localhost:4430/api/rooms/test/

################################################################
#                                                              #
#                          Room tests                          #
#                                                              #
################################################################

# ************************** CREATE ************************** #

### attention : un user peut creer plein de room: voir si on change ou non
#create room
POST https://localhost:4430/api/rooms/create_room/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTgzNzA3LCJpYXQiOjE3Mzc5NzgzMDcsImp0aSI6IjFhMWEyNmYxMmU1YjRmNzFhNDJlY2IzOWYyMjQ0YmU3IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.PD6a2L-RoEGhy-22uEl65DxOUo70E5-JG85BZ3h2ga6JoJFihgKKbRm5JDF0Kz0Jn0Q-ELqXiExcHAYKUZrxqzyXdDNm6JQsNqoG-YXgWJAe35DJs4v3mBmfxAM-WylBdDdrO1E1O1YzlR9CdK-9CMeE1s0FyF8fzVxx9jVyfo9lSml7Gn6okwx6Ubt8p_2SqKA8vnP9Rdhuo4obxZrApduAo-KCUfPQ-zHmxYCX6jEmpHyHtZMYNKxe1sEkRlzOEg6FC3e1lLYSxmf7ZaZbkqf8pIM4HjGt-UpGv1fF4Vai9KYqzQp43ARUlGrEhWbDxd-6RzNTJwiMc6RPAAK8MQ

###
#join room
POST https://localhost:4430/api/rooms/join_room/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTgzNzA3LCJpYXQiOjE3Mzc5NzgzMDcsImp0aSI6IjFhMWEyNmYxMmU1YjRmNzFhNDJlY2IzOWYyMjQ0YmU3IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.PD6a2L-RoEGhy-22uEl65DxOUo70E5-JG85BZ3h2ga6JoJFihgKKbRm5JDF0Kz0Jn0Q-ELqXiExcHAYKUZrxqzyXdDNm6JQsNqoG-YXgWJAe35DJs4v3mBmfxAM-WylBdDdrO1E1O1YzlR9CdK-9CMeE1s0FyF8fzVxx9jVyfo9lSml7Gn6okwx6Ubt8p_2SqKA8vnP9Rdhuo4obxZrApduAo-KCUfPQ-zHmxYCX6jEmpHyHtZMYNKxe1sEkRlzOEg6FC3e1lLYSxmf7ZaZbkqf8pIM4HjGt-UpGv1fF4Vai9KYqzQp43ARUlGrEhWbDxd-6RzNTJwiMc6RPAAK8MQ

# *************************** READ *************************** #

###
#list all rooms
GET https://localhost:4430/api/rooms/list_all_rooms/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTgzNzA3LCJpYXQiOjE3Mzc5NzgzMDcsImp0aSI6IjFhMWEyNmYxMmU1YjRmNzFhNDJlY2IzOWYyMjQ0YmU3IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.PD6a2L-RoEGhy-22uEl65DxOUo70E5-JG85BZ3h2ga6JoJFihgKKbRm5JDF0Kz0Jn0Q-ELqXiExcHAYKUZrxqzyXdDNm6JQsNqoG-YXgWJAe35DJs4v3mBmfxAM-WylBdDdrO1E1O1YzlR9CdK-9CMeE1s0FyF8fzVxx9jVyfo9lSml7Gn6okwx6Ubt8p_2SqKA8vnP9Rdhuo4obxZrApduAo-KCUfPQ-zHmxYCX6jEmpHyHtZMYNKxe1sEkRlzOEg6FC3e1lLYSxmf7ZaZbkqf8pIM4HjGt-UpGv1fF4Vai9KYqzQp43ARUlGrEhWbDxd-6RzNTJwiMc6RPAAK8MQ

###
#list available rooms
GET https://localhost:4430/api/rooms/list_available_rooms/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTgzNzA3LCJpYXQiOjE3Mzc5NzgzMDcsImp0aSI6IjFhMWEyNmYxMmU1YjRmNzFhNDJlY2IzOWYyMjQ0YmU3IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.PD6a2L-RoEGhy-22uEl65DxOUo70E5-JG85BZ3h2ga6JoJFihgKKbRm5JDF0Kz0Jn0Q-ELqXiExcHAYKUZrxqzyXdDNm6JQsNqoG-YXgWJAe35DJs4v3mBmfxAM-WylBdDdrO1E1O1YzlR9CdK-9CMeE1s0FyF8fzVxx9jVyfo9lSml7Gn6okwx6Ubt8p_2SqKA8vnP9Rdhuo4obxZrApduAo-KCUfPQ-zHmxYCX6jEmpHyHtZMYNKxe1sEkRlzOEg6FC3e1lLYSxmf7ZaZbkqf8pIM4HjGt-UpGv1fF4Vai9KYqzQp43ARUlGrEhWbDxd-6RzNTJwiMc6RPAAK8MQ

###
#list locked rooms
GET https://localhost:4430/api/rooms/list_locked_rooms/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTgzNzA3LCJpYXQiOjE3Mzc5NzgzMDcsImp0aSI6IjFhMWEyNmYxMmU1YjRmNzFhNDJlY2IzOWYyMjQ0YmU3IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.PD6a2L-RoEGhy-22uEl65DxOUo70E5-JG85BZ3h2ga6JoJFihgKKbRm5JDF0Kz0Jn0Q-ELqXiExcHAYKUZrxqzyXdDNm6JQsNqoG-YXgWJAe35DJs4v3mBmfxAM-WylBdDdrO1E1O1YzlR9CdK-9CMeE1s0FyF8fzVxx9jVyfo9lSml7Gn6okwx6Ubt8p_2SqKA8vnP9Rdhuo4obxZrApduAo-KCUfPQ-zHmxYCX6jEmpHyHtZMYNKxe1sEkRlzOEg6FC3e1lLYSxmf7ZaZbkqf8pIM4HjGt-UpGv1fF4Vai9KYqzQp43ARUlGrEhWbDxd-6RzNTJwiMc6RPAAK8MQ

###
#count all rooms
GET https://localhost:4430/api/rooms/count_all_rooms/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTgzNzA3LCJpYXQiOjE3Mzc5NzgzMDcsImp0aSI6IjFhMWEyNmYxMmU1YjRmNzFhNDJlY2IzOWYyMjQ0YmU3IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.PD6a2L-RoEGhy-22uEl65DxOUo70E5-JG85BZ3h2ga6JoJFihgKKbRm5JDF0Kz0Jn0Q-ELqXiExcHAYKUZrxqzyXdDNm6JQsNqoG-YXgWJAe35DJs4v3mBmfxAM-WylBdDdrO1E1O1YzlR9CdK-9CMeE1s0FyF8fzVxx9jVyfo9lSml7Gn6okwx6Ubt8p_2SqKA8vnP9Rdhuo4obxZrApduAo-KCUfPQ-zHmxYCX6jEmpHyHtZMYNKxe1sEkRlzOEg6FC3e1lLYSxmf7ZaZbkqf8pIM4HjGt-UpGv1fF4Vai9KYqzQp43ARUlGrEhWbDxd-6RzNTJwiMc6RPAAK8MQ

###
#count available rooms
GET https://localhost:4430/api/rooms/count_available_rooms/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTgzNzA3LCJpYXQiOjE3Mzc5NzgzMDcsImp0aSI6IjFhMWEyNmYxMmU1YjRmNzFhNDJlY2IzOWYyMjQ0YmU3IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.PD6a2L-RoEGhy-22uEl65DxOUo70E5-JG85BZ3h2ga6JoJFihgKKbRm5JDF0Kz0Jn0Q-ELqXiExcHAYKUZrxqzyXdDNm6JQsNqoG-YXgWJAe35DJs4v3mBmfxAM-WylBdDdrO1E1O1YzlR9CdK-9CMeE1s0FyF8fzVxx9jVyfo9lSml7Gn6okwx6Ubt8p_2SqKA8vnP9Rdhuo4obxZrApduAo-KCUfPQ-zHmxYCX6jEmpHyHtZMYNKxe1sEkRlzOEg6FC3e1lLYSxmf7ZaZbkqf8pIM4HjGt-UpGv1fF4Vai9KYqzQp43ARUlGrEhWbDxd-6RzNTJwiMc6RPAAK8MQ

###
#count locked rooms
GET https://localhost:4430/api/rooms/count_locked_rooms/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTgzNzA3LCJpYXQiOjE3Mzc5NzgzMDcsImp0aSI6IjFhMWEyNmYxMmU1YjRmNzFhNDJlY2IzOWYyMjQ0YmU3IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.PD6a2L-RoEGhy-22uEl65DxOUo70E5-JG85BZ3h2ga6JoJFihgKKbRm5JDF0Kz0Jn0Q-ELqXiExcHAYKUZrxqzyXdDNm6JQsNqoG-YXgWJAe35DJs4v3mBmfxAM-WylBdDdrO1E1O1YzlR9CdK-9CMeE1s0FyF8fzVxx9jVyfo9lSml7Gn6okwx6Ubt8p_2SqKA8vnP9Rdhuo4obxZrApduAo-KCUfPQ-zHmxYCX6jEmpHyHtZMYNKxe1sEkRlzOEg6FC3e1lLYSxmf7ZaZbkqf8pIM4HjGt-UpGv1fF4Vai9KYqzQp43ARUlGrEhWbDxd-6RzNTJwiMc6RPAAK8MQ

# ************************** DELETE ************************** #

###
#delete rooms
DELETE https://localhost:4430/api/rooms/delete_room/room_e3aaed1d/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTgzNzA3LCJpYXQiOjE3Mzc5NzgzMDcsImp0aSI6IjFhMWEyNmYxMmU1YjRmNzFhNDJlY2IzOWYyMjQ0YmU3IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.PD6a2L-RoEGhy-22uEl65DxOUo70E5-JG85BZ3h2ga6JoJFihgKKbRm5JDF0Kz0Jn0Q-ELqXiExcHAYKUZrxqzyXdDNm6JQsNqoG-YXgWJAe35DJs4v3mBmfxAM-WylBdDdrO1E1O1YzlR9CdK-9CMeE1s0FyF8fzVxx9jVyfo9lSml7Gn6okwx6Ubt8p_2SqKA8vnP9Rdhuo4obxZrApduAo-KCUfPQ-zHmxYCX6jEmpHyHtZMYNKxe1sEkRlzOEg6FC3e1lLYSxmf7ZaZbkqf8pIM4HjGt-UpGv1fF4Vai9KYqzQp43ARUlGrEhWbDxd-6RzNTJwiMc6RPAAK8MQ

################################################################
#                                                              #
#                   Room service User tests                    #
#                   (mauvais tests : a MAJ)                    #
#                                                              #
################################################################

# ************************** CREATE ************************** #

###
#create user
POST https://localhost:4430/api/rooms/create/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTgzNzA3LCJpYXQiOjE3Mzc5NzgzMDcsImp0aSI6IjFhMWEyNmYxMmU1YjRmNzFhNDJlY2IzOWYyMjQ0YmU3IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.PD6a2L-RoEGhy-22uEl65DxOUo70E5-JG85BZ3h2ga6JoJFihgKKbRm5JDF0Kz0Jn0Q-ELqXiExcHAYKUZrxqzyXdDNm6JQsNqoG-YXgWJAe35DJs4v3mBmfxAM-WylBdDdrO1E1O1YzlR9CdK-9CMeE1s0FyF8fzVxx9jVyfo9lSml7Gn6okwx6Ubt8p_2SqKA8vnP9Rdhuo4obxZrApduAo-KCUfPQ-zHmxYCX6jEmpHyHtZMYNKxe1sEkRlzOEg6FC3e1lLYSxmf7ZaZbkqf8pIM4HjGt-UpGv1fF4Vai9KYqzQp43ARUlGrEhWbDxd-6RzNTJwiMc6RPAAK8MQ

# *************************** READ *************************** #

###
#get a list of users
GET https://localhost:4430/api/rooms/list/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTgzNzA3LCJpYXQiOjE3Mzc5NzgzMDcsImp0aSI6IjFhMWEyNmYxMmU1YjRmNzFhNDJlY2IzOWYyMjQ0YmU3IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.PD6a2L-RoEGhy-22uEl65DxOUo70E5-JG85BZ3h2ga6JoJFihgKKbRm5JDF0Kz0Jn0Q-ELqXiExcHAYKUZrxqzyXdDNm6JQsNqoG-YXgWJAe35DJs4v3mBmfxAM-WylBdDdrO1E1O1YzlR9CdK-9CMeE1s0FyF8fzVxx9jVyfo9lSml7Gn6okwx6Ubt8p_2SqKA8vnP9Rdhuo4obxZrApduAo-KCUfPQ-zHmxYCX6jEmpHyHtZMYNKxe1sEkRlzOEg6FC3e1lLYSxmf7ZaZbkqf8pIM4HjGt-UpGv1fF4Vai9KYqzQp43ARUlGrEhWbDxd-6RzNTJwiMc6RPAAK8MQ

# **************************** PUT *************************** #

###
#update user
PUT https://localhost:4430/api/rooms/update/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTgzNzA3LCJpYXQiOjE3Mzc5NzgzMDcsImp0aSI6IjFhMWEyNmYxMmU1YjRmNzFhNDJlY2IzOWYyMjQ0YmU3IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.PD6a2L-RoEGhy-22uEl65DxOUo70E5-JG85BZ3h2ga6JoJFihgKKbRm5JDF0Kz0Jn0Q-ELqXiExcHAYKUZrxqzyXdDNm6JQsNqoG-YXgWJAe35DJs4v3mBmfxAM-WylBdDdrO1E1O1YzlR9CdK-9CMeE1s0FyF8fzVxx9jVyfo9lSml7Gn6okwx6Ubt8p_2SqKA8vnP9Rdhuo4obxZrApduAo-KCUfPQ-zHmxYCX6jEmpHyHtZMYNKxe1sEkRlzOEg6FC3e1lLYSxmf7ZaZbkqf8pIM4HjGt-UpGv1fF4Vai9KYqzQp43ARUlGrEhWbDxd-6RzNTJwiMc6RPAAK8MQ

# ************************** DELETE ************************** #

###
#delete user
DELETE  https://localhost:4430/api/rooms/delete/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTgzNzA3LCJpYXQiOjE3Mzc5NzgzMDcsImp0aSI6IjFhMWEyNmYxMmU1YjRmNzFhNDJlY2IzOWYyMjQ0YmU3IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.PD6a2L-RoEGhy-22uEl65DxOUo70E5-JG85BZ3h2ga6JoJFihgKKbRm5JDF0Kz0Jn0Q-ELqXiExcHAYKUZrxqzyXdDNm6JQsNqoG-YXgWJAe35DJs4v3mBmfxAM-WylBdDdrO1E1O1YzlR9CdK-9CMeE1s0FyF8fzVxx9jVyfo9lSml7Gn6okwx6Ubt8p_2SqKA8vnP9Rdhuo4obxZrApduAo-KCUfPQ-zHmxYCX6jEmpHyHtZMYNKxe1sEkRlzOEg6FC3e1lLYSxmf7ZaZbkqf8pIM4HjGt-UpGv1fF4Vai9KYqzQp43ARUlGrEhWbDxd-6RzNTJwiMc6RPAAK8MQ
