###
#check if room service is working
GET https://localhost:4430/api/rooms/test/


################################################################
#                                                              #
#       Tests Users (endpoint called by the auth service       #
#                                                              #
################################################################

###add user to db

post https://localhost:4430/api/auth/signup/
Content-Type: application/json

{
  "username": "dd",
  "password": "Pass12456!",
  "email": "d@gmail.com"
}

###
#get user token
POST https://localhost:4430/api/auth/token/
Content-Type: application/json

{
  "username": "Marine",
  "password": "MDP123!!!!gr"

}

###
#delete user
DELETE  https://localhost:4430/api/auth/delete/dd/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMTc0MTAzLCJpYXQiOjE3NDAxNjg3MDMsImp0aSI6Ijk5MjEzMzJhZDE4NTQ5NTU4YzYwOWU5NDg3Y2UxZWQzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJNYXJpbmUifQ.C4Tjq84Odd7EVQZkm4wJaV65diZaNLKbOMKVQm1ImwKY1mDZwSxrPx2WkdqM27dMHhFy743l5mYSJKE8u5xsdFjnz5lf3QDMIefe3TE11vqG7gRb-JYERjjDaqAQpF6gte-crW-FBRuI2mVTxUKmuZ7h9TJgUi5rdIb8sQ_Nma3FsQsoP4n5y6t7z4XcsI8nar99eXxi5autwlA-eP9u2Ei_Fo9mi2nwEOvNiqEzoIC13qEV-YO3OcLFJjqmZnLc37w36ti2lQ-U-Fm-G8Vk0HkvoFHCwNkoDWrjk8hP6cPkIFhOuqjkJZnX9g2miUNVQyvGgEXxVm-CiDivCC-5YA


################################################################
#                                                              #
#                          Room tests                          #
#                                                              #
################################################################

# ************************** CREATE ************************** #

### attention : un user peut creer plein de room: voir si on change ou non
#create room
POST https://localhost:4430/api/rooms/create_room/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5ODk2ODkwLCJpYXQiOjE3Mzk4OTE0OTAsImp0aSI6IjAzN2UwZGYxZTU3NDRlNzc5MzMwNzg4MWEwNGEzMmY2IiwidXNlcl9pZCI6MiwidXNlcm5hbWUiOiJkZCJ9.glV42X8poo_MPp2Y6zCQbFA91jJuZ25mRaIRbhuz7XN0lFrq-KX1wF06YZLcBGD8ZFZzO8SDpATMxj2-GgdbejPYy6WA5DxHmD1iaC4yT9TwBLb22UnQe94k75Jr8vrg3BcnKz--TICStffQMT08kpPWRkJRWzJcPT7QoRdPo6qfqp-2jPebsSdevKauKjGp7eeAt1TWl5UmVl5I-gdgB1dPULnAYOdc911zDB4aTSPDPHBUWPlWJIXE1NLcI-AYN5sUPm73GNxdKVQiXbOYS8Sdcq9qnc1UaMITyO1XytbOohopHP7WkwKDp0e1ekNQ9KAR6r7yr9Xb6vJOCJzaQg

###
#join room
POST https://localhost:4430/api/rooms/join_room/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMTc0MTAzLCJpYXQiOjE3NDAxNjg3MDMsImp0aSI6Ijk5MjEzMzJhZDE4NTQ5NTU4YzYwOWU5NDg3Y2UxZWQzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJNYXJpbmUifQ.C4Tjq84Odd7EVQZkm4wJaV65diZaNLKbOMKVQm1ImwKY1mDZwSxrPx2WkdqM27dMHhFy743l5mYSJKE8u5xsdFjnz5lf3QDMIefe3TE11vqG7gRb-JYERjjDaqAQpF6gte-crW-FBRuI2mVTxUKmuZ7h9TJgUi5rdIb8sQ_Nma3FsQsoP4n5y6t7z4XcsI8nar99eXxi5autwlA-eP9u2Ei_Fo9mi2nwEOvNiqEzoIC13qEV-YO3OcLFJjqmZnLc37w36ti2lQ-U-Fm-G8Vk0HkvoFHCwNkoDWrjk8hP6cPkIFhOuqjkJZnX9g2miUNVQyvGgEXxVm-CiDivCC-5YA

# *************************** READ *************************** #

###
#list all rooms
GET https://localhost:4430/api/rooms/list_all_rooms/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMTc0MTAzLCJpYXQiOjE3NDAxNjg3MDMsImp0aSI6Ijk5MjEzMzJhZDE4NTQ5NTU4YzYwOWU5NDg3Y2UxZWQzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJNYXJpbmUifQ.C4Tjq84Odd7EVQZkm4wJaV65diZaNLKbOMKVQm1ImwKY1mDZwSxrPx2WkdqM27dMHhFy743l5mYSJKE8u5xsdFjnz5lf3QDMIefe3TE11vqG7gRb-JYERjjDaqAQpF6gte-crW-FBRuI2mVTxUKmuZ7h9TJgUi5rdIb8sQ_Nma3FsQsoP4n5y6t7z4XcsI8nar99eXxi5autwlA-eP9u2Ei_Fo9mi2nwEOvNiqEzoIC13qEV-YO3OcLFJjqmZnLc37w36ti2lQ-U-Fm-G8Vk0HkvoFHCwNkoDWrjk8hP6cPkIFhOuqjkJZnX9g2miUNVQyvGgEXxVm-CiDivCC-5YA

###
#list available rooms
GET https://localhost:4430/api/rooms/list_available_rooms/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMTc0MTAzLCJpYXQiOjE3NDAxNjg3MDMsImp0aSI6Ijk5MjEzMzJhZDE4NTQ5NTU4YzYwOWU5NDg3Y2UxZWQzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJNYXJpbmUifQ.C4Tjq84Odd7EVQZkm4wJaV65diZaNLKbOMKVQm1ImwKY1mDZwSxrPx2WkdqM27dMHhFy743l5mYSJKE8u5xsdFjnz5lf3QDMIefe3TE11vqG7gRb-JYERjjDaqAQpF6gte-crW-FBRuI2mVTxUKmuZ7h9TJgUi5rdIb8sQ_Nma3FsQsoP4n5y6t7z4XcsI8nar99eXxi5autwlA-eP9u2Ei_Fo9mi2nwEOvNiqEzoIC13qEV-YO3OcLFJjqmZnLc37w36ti2lQ-U-Fm-G8Vk0HkvoFHCwNkoDWrjk8hP6cPkIFhOuqjkJZnX9g2miUNVQyvGgEXxVm-CiDivCC-5YA

###
#list locked rooms
GET https://localhost:4430/api/rooms/list_locked_rooms/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMTc0MTAzLCJpYXQiOjE3NDAxNjg3MDMsImp0aSI6Ijk5MjEzMzJhZDE4NTQ5NTU4YzYwOWU5NDg3Y2UxZWQzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJNYXJpbmUifQ.C4Tjq84Odd7EVQZkm4wJaV65diZaNLKbOMKVQm1ImwKY1mDZwSxrPx2WkdqM27dMHhFy743l5mYSJKE8u5xsdFjnz5lf3QDMIefe3TE11vqG7gRb-JYERjjDaqAQpF6gte-crW-FBRuI2mVTxUKmuZ7h9TJgUi5rdIb8sQ_Nma3FsQsoP4n5y6t7z4XcsI8nar99eXxi5autwlA-eP9u2Ei_Fo9mi2nwEOvNiqEzoIC13qEV-YO3OcLFJjqmZnLc37w36ti2lQ-U-Fm-G8Vk0HkvoFHCwNkoDWrjk8hP6cPkIFhOuqjkJZnX9g2miUNVQyvGgEXxVm-CiDivCC-5YA

###
#count all rooms
GET https://localhost:4430/api/rooms/count_all_rooms/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMTc0MTAzLCJpYXQiOjE3NDAxNjg3MDMsImp0aSI6Ijk5MjEzMzJhZDE4NTQ5NTU4YzYwOWU5NDg3Y2UxZWQzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJNYXJpbmUifQ.C4Tjq84Odd7EVQZkm4wJaV65diZaNLKbOMKVQm1ImwKY1mDZwSxrPx2WkdqM27dMHhFy743l5mYSJKE8u5xsdFjnz5lf3QDMIefe3TE11vqG7gRb-JYERjjDaqAQpF6gte-crW-FBRuI2mVTxUKmuZ7h9TJgUi5rdIb8sQ_Nma3FsQsoP4n5y6t7z4XcsI8nar99eXxi5autwlA-eP9u2Ei_Fo9mi2nwEOvNiqEzoIC13qEV-YO3OcLFJjqmZnLc37w36ti2lQ-U-Fm-G8Vk0HkvoFHCwNkoDWrjk8hP6cPkIFhOuqjkJZnX9g2miUNVQyvGgEXxVm-CiDivCC-5YA

###
#count available rooms
GET https://localhost:4430/api/rooms/count_available_rooms/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMTc0MTAzLCJpYXQiOjE3NDAxNjg3MDMsImp0aSI6Ijk5MjEzMzJhZDE4NTQ5NTU4YzYwOWU5NDg3Y2UxZWQzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJNYXJpbmUifQ.C4Tjq84Odd7EVQZkm4wJaV65diZaNLKbOMKVQm1ImwKY1mDZwSxrPx2WkdqM27dMHhFy743l5mYSJKE8u5xsdFjnz5lf3QDMIefe3TE11vqG7gRb-JYERjjDaqAQpF6gte-crW-FBRuI2mVTxUKmuZ7h9TJgUi5rdIb8sQ_Nma3FsQsoP4n5y6t7z4XcsI8nar99eXxi5autwlA-eP9u2Ei_Fo9mi2nwEOvNiqEzoIC13qEV-YO3OcLFJjqmZnLc37w36ti2lQ-U-Fm-G8Vk0HkvoFHCwNkoDWrjk8hP6cPkIFhOuqjkJZnX9g2miUNVQyvGgEXxVm-CiDivCC-5YA

###
#count locked rooms
GET https://localhost:4430/api/rooms/count_locked_rooms/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMTc0MTAzLCJpYXQiOjE3NDAxNjg3MDMsImp0aSI6Ijk5MjEzMzJhZDE4NTQ5NTU4YzYwOWU5NDg3Y2UxZWQzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJNYXJpbmUifQ.C4Tjq84Odd7EVQZkm4wJaV65diZaNLKbOMKVQm1ImwKY1mDZwSxrPx2WkdqM27dMHhFy743l5mYSJKE8u5xsdFjnz5lf3QDMIefe3TE11vqG7gRb-JYERjjDaqAQpF6gte-crW-FBRuI2mVTxUKmuZ7h9TJgUi5rdIb8sQ_Nma3FsQsoP4n5y6t7z4XcsI8nar99eXxi5autwlA-eP9u2Ei_Fo9mi2nwEOvNiqEzoIC13qEV-YO3OcLFJjqmZnLc37w36ti2lQ-U-Fm-G8Vk0HkvoFHCwNkoDWrjk8hP6cPkIFhOuqjkJZnX9g2miUNVQyvGgEXxVm-CiDivCC-5YA

# ************************** DELETE ************************** #

###
#delete rooms
DELETE https://localhost:4430/api/rooms/delete_room/room_e3aaed1d/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMTc0MTAzLCJpYXQiOjE3NDAxNjg3MDMsImp0aSI6Ijk5MjEzMzJhZDE4NTQ5NTU4YzYwOWU5NDg3Y2UxZWQzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJNYXJpbmUifQ.C4Tjq84Odd7EVQZkm4wJaV65diZaNLKbOMKVQm1ImwKY1mDZwSxrPx2WkdqM27dMHhFy743l5mYSJKE8u5xsdFjnz5lf3QDMIefe3TE11vqG7gRb-JYERjjDaqAQpF6gte-crW-FBRuI2mVTxUKmuZ7h9TJgUi5rdIb8sQ_Nma3FsQsoP4n5y6t7z4XcsI8nar99eXxi5autwlA-eP9u2Ei_Fo9mi2nwEOvNiqEzoIC13qEV-YO3OcLFJjqmZnLc37w36ti2lQ-U-Fm-G8Vk0HkvoFHCwNkoDWrjk8hP6cPkIFhOuqjkJZnX9g2miUNVQyvGgEXxVm-CiDivCC-5YA
