###
#check if service can access protected view
GET https://localhost:4430/api/users/protected/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2MjU5NDYyLCJpYXQiOjE3MzYyNTQwNjIsImp0aSI6IjBjYWI1MThjMTJiNTQxZDZhMjM2MmZlMWIxNDI3NjBjIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJ0ZXN0X3VzZXIifQ.Neb23t9S1XKbrfhqtXN6oO6YB7oYRLTw7-jRWQhjX4YpqP5z_ap-XK84FVqnzSfZzDkZJ7Nz2A2HJSgA8eWl4W4vEHkQ9ssKAGtctkgae6ht73ZhVLlXYFBKYJiYnTOvN_ZzyaPqlyWujh2dr_tvF2cViujIkNu3U3tCqkU5RmQCD9Jccgs63FT8NTR-MnEvBpo_jErLrTeKGDBtmlImo_kk3xAHE-Meh4sEXpwo0c49_PmWAN9tAWC2vKXVlnDCvXFoO31nhJMnv2uiPpxPcaN9X8oVBkHBAH0dIxoP-_V3WWXdXlaHrALmN1o4dmBITTOT2ItsIH5hbVePjoR6cA