POST https://localhost:4430/api/auth/login
Content-Type: application/json

{
  "username": "singeuse",
  "password": "pass123"
}

###

POST https://localhost:4430/api/users/create/
Content-Type: application/json

{
  "username": ""

}
###

get https://localhost:4430/api/auth/test_token
Content-Type: application/json
Authorization: Token 60f89c7f4099aeb971c421fbe90495f87c338299

{}

###
get https://localhost:4430/api/users/singeue_pseudo/